/**
 * Topic inference for Glassdoor occurrence → heat (signals only).
 * Aligns loosely with seed/teaching topics used in Mode A rooms.
 */

export type TopicRule = {
  topic_id: string;
  patterns: RegExp[];
};

/** Ordered rules — first match wins. */
export const TOPIC_RULES: TopicRule[] = [
  {
    topic_id: "lbo",
    patterns: [
      /\blbo\b/i,
      /leveraged buyout/i,
      /paper lbo/i,
      /\bmoic\b/i,
      /\birr\b/i,
      /debt paydown/i,
      /cash sweep/i,
      /sources? and uses?/i,
      /entry multiple/i,
      /exit multiple/i,
      /sponsor returns?/i,
      /dividend recap/i,
      /management rollover/i,
    ],
  },
  {
    topic_id: "valuation",
    patterns: [
      /\bdcf\b/i,
      /discounted cash flow/i,
      /\bwacc\b/i,
      /\bcapm\b/i,
      /comparable compan/i,
      /\bcomps\b/i,
      /trading multipl/i,
      /transaction multipl/i,
      /precedent transaction/i,
      /\bvaluation\b/i,
      /terminal value/i,
      /gordon growth/i,
      /perpetuity growth/i,
      /free cash flow/i,
      /\bfcf\b/i,
      /levered fcf/i,
      /unlevered fcf/i,
      /how do i get to (levered |unlevered )?fcf/i,
      /unlevered/i,
      /\bddm\b/i,
      /dividend discount model/i,
    ],
  },
  {
    topic_id: "enterprise_value",
    patterns: [
      /enterprise value/i,
      /equity value/i,
      /\bev\b.*\bequity\b/i,
      /\bequity\b.*\bev\b/i,
      /net debt/i,
      /minority interest/i,
      /preferred stock/i,
      /treasury stock method/i,
      /fully diluted shares?/i,
    ],
  },
  {
    topic_id: "working_capital",
    patterns: [
      /working capital/i,
      /\bnwc\b/i,
      /accounts? receivable/i,
      /accounts? payable/i,
      /cash conversion cycle/i,
      /inventory turnover/i,
    ],
  },
  {
    topic_id: "accounting",
    patterns: [
      /three (financial )?statements/i,
      /income statement/i,
      /balance sheet/i,
      /cash flow statement/i,
      /depreciation/i,
      /amortization/i,
      /\bgaap\b/i,
      /goodwill/i,
      /impairment/i,
      /write-?down/i,
      /deferred tax/i,
      /revenue recognition/i,
      /net income/i,
      /\bcogs\b/i,
      /capital expenditure/i,
      /\bcapex\b/i,
    ],
  },
  {
    topic_id: "merger_models",
    patterns: [
      /\bmerger\b/i,
      /\baccretion\b/i,
      /\bdilution\b/i,
      /\bm\s*&\s*a\b/i,
      /mergers? and acquisitions?/i,
      /merger model/i,
      /accretive/i,
      /dilutive/i,
      /purchase accounting/i,
      /pro forma eps/i,
      /deal synergies/i,
      /stock (deal|consideration)/i,
      /cash (deal|consideration)/i,
      /exchange ratio/i,
    ],
  },
  {
    topic_id: "credit",
    patterns: [
      /credit analysis/i,
      /credit agreement/i,
      /credit facility/i,
      /credit metrics?/i,
      /credit risk/i,
      /credit spread/i,
      /credit rating/i,
      /debt capacity/i,
      /\bcovenants?\b/i,
      /interest coverage/i,
      /leverage ratio/i,
      /loan-?to-?value/i,
      /\bltv\b/i,
      /private credit/i,
      /leveraged finance/i,
      /high yield/i,
      /default risk/i,
    ],
  },
  {
    topic_id: "capital_structure",
    patterns: [
      /capital structure/i,
      /cost of (debt|equity|capital)/i,
      /\bleverage\b/i,
      /debt (vs\.?|versus) equity/i,
      /debt financing/i,
      /equity financing/i,
      /convertible debt/i,
      /preferred equity/i,
      /\brevolver\b/i,
      /term loan/i,
      /senior debt/i,
      /subordinated debt/i,
    ],
  },
  {
    topic_id: "investment_thesis",
    patterns: [
      /investment thesis/i,
      /underwrite/i,
      /why (this|that) (deal|investment)/i,
      /why (this|that) company as (an? )?investment/i,
      /would you (invest in|acquire|buy)/i,
      /attractive investment/i,
      /good investment/i,
      /pitch me (a|an) (stock|investment|company)/i,
      /stock pitch/i,
      /recent deal/i,
      /deal (you|i) (was |have )?follow/i,
      /investment idea/i,
      /long pitch/i,
      /short pitch/i,
      /buy or sell/i,
      /growth drivers?/i,
    ],
  },
  {
    topic_id: "due_diligence",
    patterns: [
      /due diligence/i,
      /\bdd\b/i,
      /quality of earnings/i,
      /\bqoe\b/i,
      /commercial diligence/i,
      /customer calls?/i,
      /\bcim\b/i,
      /data room/i,
      /management presentation/i,
    ],
  },
  {
    topic_id: "restructuring",
    patterns: [
      /restructur/i,
      /bankrupt/i,
      /distressed/i,
      /chapter 11/i,
      /liquidation/i,
      /recovery value/i,
      /waterfall/i,
      /debtor-?in-?possession/i,
      /\bdip financing\b/i,
    ],
  },
  {
    topic_id: "returns",
    patterns: [
      /\breturns?\b/i,
      /\bmoic\b/i,
      /\birr\b/i,
      /cash-?on-?cash/i,
      /multiple of (invested )?money/i,
      /\broic\b/i,
      /return on invested capital/i,
      /hurdle rate/i,
    ],
  },
  {
    topic_id: "value_creation",
    patterns: [
      /value creation/i,
      /operational improve/i,
      /add-?on acquisition/i,
      /tuck-?in acquisition/i,
      /platform acquisition/i,
      /portfolio company/i,
      /margin expansion/i,
      /cost cuts?/i,
      /revenue growth/i,
      /100-?day plan/i,
    ],
  },
  {
    topic_id: "industry_coverage",
    patterns: [
      /industry coverage/i,
      /coverage group/i,
      /sector trends?/i,
      /industry trends?/i,
      /which (industry|sector).*(follow|interested)/i,
      /what (industry|sector).*(follow|interested)/i,
      /(healthcare|technology|fig|industrials|consumer|retail|energy) (group|coverage|sector)/i,
    ],
  },
  {
    topic_id: "markets",
    patterns: [
      /current markets?/i,
      /market conditions?/i,
      /market news/i,
      /recent market/i,
      /recent (news|transaction)/i,
      /in the news/i,
      /stock market/i,
      /view (the )?(real estate |equity )?market/i,
      /yield curve/i,
      /interest rates?/i,
      /\bfed\b/i,
      /federal reserve/i,
      /inflation/i,
      /macroeconomic/i,
      /\bmacro\b/i,
      /\bs\s*&\s*p\s*500\b/i,
    ],
  },
  {
    topic_id: "brainteasers",
    patterns: [
      /brain ?teasers?/i,
      /mental math/i,
      /market sizing/i,
      /how many .* (fit|are in|in a)\b/i,
      /(tennis|golf|ping pong) balls?/i,
      /manhole covers?/i,
      /probability (question|problem|puzzle)/i,
      /coin flips?/i,
      /\bdice\b/i,
    ],
  },
  {
    topic_id: "behavioral",
    patterns: [
      /tell me about yourself/i,
      /walk me through your (resume|cv)/i,
      /tell me about your (resume|cv)/i,
      /why (ib|investment banking|private equity|banking|our firm)/i,
      /why (do you )?(want to )?(work|join|apply).*(firm|bank|company|team|position)/i,
      /why (did you choose|would you (like to )?work)/i,
      /why .{0,40}(goldman|morgan stanley|jpmorgan|blackstone|kkr|evercore|lazard|barclays|ubs)/i,
      /where .{0,20}(see yourself|in 5 years)/i,
      /hobbies/i,
      /strengths? and weaknesses?/i,
      /\bfit\b/i,
      /behavioral/i,
      /tell me about a time/i,
      /teamwork/i,
      /\bconflict\b/i,
      /\bfailure\b/i,
      /leadership/i,
    ],
  },
];

export function inferTopic(text: string): string {
  for (const rule of TOPIC_RULES) {
    if (rule.patterns.some((p) => p.test(text))) return rule.topic_id;
  }
  return "untagged";
}

/** Intensity formula mirrors published.v_firm_topic_heat: least(1, ln(n+1)/ln(50)). */
export function intensityFromCount(sampleSize: number): number {
  if (sampleSize <= 0) return 0;
  return Math.min(1, Math.log(sampleSize + 1) / Math.log(50));
}
