-- 059_diagrams_core.sql
-- P2.9 diagram coverage (plan 2026-09-23-001).
-- Upgrades 8 existing mermaid diagrams to richer version-2 bodies and adds
-- 10 new ones (comps, full 3-statement, debt schedule, working capital,
-- merger model, returns attribution, DDM, football field, restructuring and PE waterfalls).
-- Links 400 export questions to diagrams by keyword rules (507 rows).
-- Rows whose question is absent from canonical.canonical_questions are skipped by the join.
-- Generated by scripts/curriculum/build-migrations.ts from apps/web/lib/data/curriculum. Do not edit by hand.

INSERT INTO canonical.diagrams (id, slug, title, diagram_type, a11y_fallback)
VALUES
    ('diag_three_statement', 'three-statement-linkages', 'Three-statement linkages', 'finance-flow', 'Net income from the income statement is the first line of cash from operations and, after dividends, flows into retained earnings on the balance sheet. D&A is a non-cash expense: it is added back in cash from operations and reduces PP&E. Cash from operations, investing and financing sum to the net change in cash, which updates the balance sheet cash line.'),
    ('diag_ev_bridge', 'ev-equity-bridge', 'EV to Equity Bridge', 'finance-flow', 'Start from enterprise value, the value of the core operations to all capital providers. Subtract debt, preferred stock and non-controlling interest, which are claims of other investors. Add cash and non-operating assets such as equity investments. The result is equity value for common shareholders; dividing by diluted shares gives the implied share price. Running the steps in reverse takes you from equity value to enterprise value.'),
    ('diag_dcf_wacc', 'dcf-wacc-flow', 'DCF and WACC Flow', 'finance-flow', 'Forecast revenue down to EBIT, tax it to NOPAT, then add back D&A and subtract capex and the increase in net working capital to get unlevered free cash flow. Discount each year''s UFCF and a terminal value (Gordon growth or exit multiple) at WACC and sum them to enterprise value. Bridge to equity value by subtracting net debt, preferred stock and non-controlling interest and adding non-operating assets, then divide by diluted shares for an implied share price.'),
    ('diag_lbo_sources_uses', 'lbo-sources-uses', 'LBO Sources and Uses', 'finance-flow', 'Uses are what the deal must pay for: the target''s equity at the offer price times diluted shares, refinancing of existing debt, transaction and financing fees, and any cash left on the balance sheet. Sources fund those uses: senior secured debt, junior debt such as high-yield notes, management rollover and sponsor equity. Sponsor equity is the plug that makes total sources equal total uses.'),
    ('diag_wacc_build', 'wacc-build-up', 'WACC build-up', 'finance-flow', 'Cost of equity comes from CAPM: the risk-free rate plus levered beta times the equity risk premium, where beta is unlevered from peers and relevered at the target capital structure. Cost of debt is the pre-tax yield times one minus the tax rate because interest is tax-deductible. WACC weights the two by market-value equity and debt proportions, and it is the rate used to discount unlevered free cash flow and terminal value.'),
    ('diag_accretion_dilution', 'accretion-dilution', 'Accretion and dilution', 'finance-flow', 'Add acquirer and target net income, add after-tax synergies, and subtract the after-tax costs of the deal: interest income lost on cash used, interest on new debt, and extra D&A from asset write-ups. Divide by the acquirer''s shares plus any new shares issued to get pro forma EPS. If pro forma EPS is higher than the acquirer''s standalone EPS the deal is accretive; if lower it is dilutive.'),
    ('diag_moic_irr', 'moic-irr', 'MOIC and IRR', 'finance-flow', 'MOIC is total equity proceeds divided by equity invested and ignores time. IRR is the discount rate that sets the net present value of the equity cash flows to zero; with a single exit it equals MOIC to the power of one over the holding period, minus one. Rules of thumb: 2.0x over 3 years is about 26%, 2.0x over 5 years about 15%, and 3.0x over 5 years about 25%. The same MOIC over a longer hold means a lower IRR.'),
    ('diag_paper_lbo_returns', 'paper-lbo-returns', 'Paper LBO returns bridge', 'finance-flow', 'Paper LBO: buy EBITDA of 100 at 10.0x for an enterprise value of 1,000, funded with 600 of debt and 400 of sponsor equity. Over five years EBITDA grows to 150 and 300 of cumulative free cash flow repays debt down to 300. Exiting at 10.0x gives an enterprise value of 1,500 and exit equity of 1,200, a 3.0x MOIC and roughly 25% IRR.'),
    ('diag_three_statement_linkages', 'three-statement-full-linkages', 'Full three-statement linkages', 'finance-flow', 'Full linkages: EBITDA less D&A and interest, after tax, is net income. Net income starts cash from operations, D&A is added back, and an increase in net working capital (receivables plus inventory minus payables) uses cash. Capex in investing cash flow increases PP&E while depreciation reduces it. Debt issuance or repayment in financing cash flow changes the debt balance, and the debt balance times the interest rate drives interest expense. Net income less dividends rolls into retained earnings, and the three cash flow sections sum to the change in cash on the balance sheet, which keeps assets equal to liabilities plus equity.'),
    ('diag_comps_precedents', 'comps-precedents', 'Trading comps and precedent transactions', 'finance-flow', 'Screen for comparable companies on industry, size, growth, margins and geography. Trading comps use public peers'' current multiples such as EV/EBITDA and P/E; precedent transactions use the multiples paid in past acquisitions, which include a control premium and so are usually higher. Choose a range around the median, for example 8.0x to 10.0x, and apply it to the target''s EBITDA of 50 for an implied enterprise value of 400 to 500. Subtract net debt of 100 for equity value of 300 to 400, or 15.00 to 20.00 per share on 20 million diluted shares.'),
    ('diag_debt_schedule', 'debt-schedule-revolver', 'Debt schedule and revolver', 'finance-flow', 'Start with free cash flow after interest and taxes and add beginning cash above the minimum cash balance to get cash available for debt repayment. Pay mandatory amortization first. If cash is left over, sweep it into optional repayments, paying down the revolver first and then prepayable term loans. If there is a shortfall, draw on the revolver up to its commitment. Ending balances drive interest expense, which feeds back into the income statement; using average balances creates a circular reference.'),
    ('diag_working_capital', 'working-capital-cycle', 'Working capital cycle', 'finance-flow', 'Cash buys inventory, inventory is sold on credit and becomes accounts receivable, and receivables are collected back into cash. Accounts payable is supplier credit that delays cash going out. The cash conversion cycle is days inventory outstanding plus days sales outstanding minus days payable outstanding. When operating working capital increases, cash from operations falls: higher receivables or inventory use cash, while higher payables or deferred revenue free up cash.'),
    ('diag_merger_model', 'merger-model', 'Merger model: sources and uses to pro forma EPS', 'finance-flow', 'Set the purchase price (offer price times target diluted shares, plus refinanced debt and fees) and fund it in sources and uses with cash, new debt or new acquirer stock. Cash costs forgone interest income, debt costs after-tax interest, and stock costs extra shares, with a cost equal to one over the acquirer''s P/E. The purchase price allocation writes up assets and records goodwill, and write-ups create extra D&A. Pro forma net income is both companies'' net income plus after-tax synergies minus these costs; divide by pro forma shares and compare with the acquirer''s standalone EPS to see whether the deal is accretive or dilutive.'),
    ('diag_returns_attribution', 'returns-attribution', 'Returns attribution: growth, multiple, deleveraging', 'finance-flow', 'Returns attribution for a deal bought at 10.0x EBITDA of 100 (enterprise value 1,000, net debt 600, equity 400) and sold at 11.0x EBITDA of 150 (enterprise value 1,650, net debt 300, equity 1,350). The equity gain of 950, about a 3.4x MOIC, splits into EBITDA growth of 500 (50 of new EBITDA at the entry multiple), multiple expansion of 150 (1.0x on exit EBITDA of 150) and deleveraging of 300 (net debt falling from 600 to 300).'),
    ('diag_ddm', 'dividend-discount-model', 'Dividend discount model for banks', 'finance-flow', 'A dividend discount model values a bank''s equity directly. Project net income, retain enough earnings to keep regulatory capital (for example CET1) at the target ratio as the balance sheet grows, and treat the rest as dividends. Discount the dividends and a terminal value, from Gordon growth on the next dividend or a price to tangible book or P/E multiple, at the cost of equity. The sum is equity value, with no enterprise value bridge, because debt and deposits are operating raw material for a bank. Divide by diluted shares for value per share.'),
    ('diag_football_field', 'football-field', 'Valuation football field', 'finance-chart', 'A football field lines up the implied share price range from each method: 52-week trading range 38 to 52, trading comps 40 to 55, precedent transactions 48 to 63, DCF 45 to 70, and an LBO at a 20 to 25 percent IRR 36 to 50. Precedents usually sit above trading comps because of the control premium, and the LBO often sets a floor. The overlap, here about 48 to 55 against a current price of 42, guides the recommended range.'),
    ('diag_restructuring_waterfall', 'restructuring-waterfall', 'Restructuring recovery waterfall', 'finance-flow', 'Absolute priority waterfall on 800 of distributable value: administrative and priority claims of 50 and senior secured debt of 500 are paid in full, leaving 250 for senior unsecured notes of 400, a 62.5 percent recovery. The unsecured notes are the fulcrum security, the first class that is not paid in full, and usually receive the reorganised company''s equity. Subordinated notes and existing equity recover nothing.'),
    ('diag_pe_distribution_waterfall', 'pe-distribution-waterfall', 'PE fund distribution waterfall', 'finance-flow', 'A European, whole-fund distribution waterfall: exit proceeds first return all contributed capital to the limited partners, then pay them a preferred return, typically an 8 percent annual hurdle. A GP catch-up then sends most distributions to the general partner until it has received 20 percent of total profits, after which profits split 80 percent to LPs and 20 percent carried interest to the GP. The management fee of roughly 1.5 to 2 percent of commitments a year is separate and pays for the GP''s operations.')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    diagram_type = EXCLUDED.diagram_type,
    a11y_fallback = EXCLUDED.a11y_fallback;

INSERT INTO canonical.diagram_versions (id, diagram_id, version, format, body)
VALUES
    (
        'diag_three_statement_v2',
        'diag_three_statement',
        '2',
        'mermaid',
        $$flowchart LR
  subgraph IS["Income statement"]
    NI["Net income"]
    DA["D&A expense"]
  end
  subgraph CFS["Cash flow statement"]
    CFO["Cash from operations"]
    CFI["Cash from investing"]
    CFF["Cash from financing"]
    NCC["Net change in cash"]
  end
  subgraph BS["Balance sheet"]
    Cash["Cash"]
    PPE["PP&E"]
    RE["Retained earnings"]
  end
  NI -->|"top line of CFO"| CFO
  DA -->|"added back, non-cash"| CFO
  DA -->|"reduces"| PPE
  NI -->|"less dividends"| RE
  CFO --> NCC
  CFI --> NCC
  CFF --> NCC
  NCC -->|"beginning cash + change"| Cash$$
    ),
    (
        'diag_ev_bridge_v2',
        'diag_ev_bridge',
        '2',
        'mermaid',
        $$flowchart LR
  EV["Enterprise value<br/>core operations, all capital providers"] --> D["− Total debt"]
  D --> P["− Preferred stock"]
  P --> N["− Non-controlling interest"]
  N --> C["+ Cash and equivalents"]
  C --> I["+ Equity investments and other non-operating assets"]
  I --> Eq["Equity value<br/>common shareholders only"]
  Eq --> PS["÷ Diluted shares = implied share price"]$$
    ),
    (
        'diag_dcf_wacc_v2',
        'diag_dcf_wacc',
        '2',
        'mermaid',
        $$flowchart LR
  Rev["Revenue forecast"] --> EBIT["EBIT"]
  EBIT --> NOPAT["NOPAT = EBIT × (1 − tax rate)"]
  NOPAT --> UFCF["Unlevered FCF = NOPAT + D&A − capex − increase in NWC"]
  UFCF --> PV["PV of forecast-period UFCF"]
  UFCF --> TV["Terminal value<br/>Gordon growth or exit multiple"]
  TV --> PVTV["PV of terminal value"]
  WACC["WACC"] -.->|"discount rate"| PV
  WACC -.->|"discount rate"| PVTV
  PV --> EV["Enterprise value"]
  PVTV --> EV
  EV --> Br["− net debt, preferred, NCI<br/>+ non-operating assets"]
  Br --> Eq["Equity value ÷ diluted shares = implied share price"]$$
    ),
    (
        'diag_lbo_sources_uses_v2',
        'diag_lbo_sources_uses',
        '2',
        'mermaid',
        $$flowchart LR
  subgraph Sources["Sources"]
    SD["Senior secured debt<br/>term loans, revolver draw"]
    JD["Junior debt<br/>high-yield notes, mezzanine"]
    RO["Management rollover equity"]
    SE["Sponsor equity, the plug"]
  end
  subgraph Uses["Uses"]
    EqP["Purchase target equity<br/>offer price × diluted shares"]
    Refi["Refinance existing debt"]
    Fees["Transaction and financing fees"]
    MC["Cash to balance sheet"]
  end
  SD --> T["Total sources = total uses"]
  JD --> T
  RO --> T
  SE --> T
  T --> EqP
  T --> Refi
  T --> Fees
  T --> MC$$
    ),
    (
        'diag_wacc_build_v2',
        'diag_wacc_build',
        '2',
        'mermaid',
        $$flowchart LR
  Rf["Risk-free rate"] --> Ke["Cost of equity = Rf + levered beta × ERP"]
  B["Peer betas: unlever, take median,<br/>relever at target D/E"] --> Ke
  ERP["Equity risk premium"] --> Ke
  Kd["Pre-tax cost of debt<br/>yield on the company's debt"] --> AT["After-tax cost of debt = Kd × (1 − t)"]
  Ke --> W["WACC = E/V × Ke + D/V × Kd × (1 − t)"]
  AT --> W
  Wt["Target capital structure<br/>market-value weights E/V and D/V"] --> W
  W --> Use["Discount unlevered FCF and terminal value"]$$
    ),
    (
        'diag_accretion_dilution_v2',
        'diag_accretion_dilution',
        '2',
        'mermaid',
        $$flowchart TB
  A["Acquirer net income"] --> PF["Pro forma net income"]
  T["Target net income"] --> PF
  S["+ After-tax synergies"] --> PF
  C["− Forgone interest on cash × (1 − t)<br/>− New debt interest × (1 − t)<br/>− New D&A on write-ups × (1 − t)"] --> PF
  Sh["Acquirer shares + new shares issued"] --> EPS
  PF --> EPS["Pro forma EPS = pro forma net income ÷ pro forma shares"]
  EPS --> Cmp{"Compare with acquirer standalone EPS"}
  Cmp -->|"higher"| Acc["Accretive"]
  Cmp -->|"lower"| Dil["Dilutive"]$$
    ),
    (
        'diag_moic_irr_v2',
        'diag_moic_irr',
        '2',
        'mermaid',
        $$flowchart LR
  In["Equity invested at entry, year 0"] --> M["MOIC = total equity proceeds ÷ equity invested"]
  Out["Equity proceeds at exit, year n<br/>plus any interim dividends"] --> M
  M --> I["IRR = rate that sets NPV of equity cash flows to zero<br/>single exit: MOIC^(1/n) − 1"]
  I --> R["Rules of thumb<br/>2.0x in 3 yrs ≈ 26%, 2.0x in 5 yrs ≈ 15%<br/>3.0x in 5 yrs ≈ 25%"]
  I -.->|"time matters"| Tm["Same MOIC over a longer hold = lower IRR"]$$
    ),
    (
        'diag_paper_lbo_returns_v2',
        'diag_paper_lbo_returns',
        '2',
        'mermaid',
        $$flowchart TB
  E["Entry: EBITDA 100 × 10.0x = EV 1,000"] --> F["Funding: debt 600 (6.0x), sponsor equity 400"]
  F --> O["5-year hold: EBITDA grows to 150<br/>cumulative FCF of 300 repays debt to 300"]
  O --> X["Exit: EBITDA 150 × 10.0x = EV 1,500"]
  X --> XE["Exit equity = 1,500 − 300 net debt = 1,200"]
  XE --> R["MOIC = 1,200 ÷ 400 = 3.0x, IRR ≈ 25%"]$$
    ),
    (
        'diag_three_statement_linkages_v1',
        'diag_three_statement_linkages',
        '1',
        'mermaid',
        $$flowchart LR
  subgraph IS["Income statement"]
    Rev["Revenue − COGS − OpEx = EBITDA"]
    DA["D&A"]
    Int["Interest expense"]
    NI["Net income = (EBITDA − D&A − interest) × (1 − t)"]
  end
  subgraph CFS["Cash flow statement"]
    CFO["CFO = NI + D&A − increase in NWC"]
    CFI["CFI = − capex"]
    CFF["CFF = debt issued − debt repaid − dividends"]
    Net["Net change in cash"]
  end
  subgraph BS["Balance sheet"]
    Cash["Cash"]
    NWC["AR + inventory − AP"]
    PPE["PP&E"]
    Debt["Debt"]
    RE["Retained earnings"]
  end
  Rev --> NI
  DA --> NI
  Int --> NI
  NI --> CFO
  DA -.->|"add back"| CFO
  NWC -.->|"increase uses cash"| CFO
  CFI -->|"capex adds"| PPE
  DA -.->|"depreciation reduces"| PPE
  CFF -->|"issuance or repayment"| Debt
  Debt -.->|"balance × rate"| Int
  NI -->|"NI − dividends"| RE
  CFO --> Net
  CFI --> Net
  CFF --> Net
  Net -->|"beginning + change = ending"| Cash$$
    ),
    (
        'diag_comps_precedents_v1',
        'diag_comps_precedents',
        '1',
        'mermaid',
        $$flowchart LR
  Scr["Screen peers: industry, size,<br/>growth, margins, geography"] --> TC["Trading comps<br/>peers' current EV/EBITDA, EV/Revenue, P/E"]
  Scr --> PT["Precedent transactions<br/>EV paid ÷ LTM EBITDA in past deals"]
  TC --> St["Pick a range: 25th–75th percentile around the median"]
  PT -->|"includes control premium, usually higher"| St
  St --> Ap["Apply to target metric<br/>8.0x–10.0x × EBITDA of 50"]
  Ap --> IEV["Implied EV range: 400–500"]
  IEV --> IEq["− net debt of 100 = equity value 300–400<br/>÷ 20m diluted shares = 15.00–20.00 per share"]$$
    ),
    (
        'diag_debt_schedule_v1',
        'diag_debt_schedule',
        '1',
        'mermaid',
        $$flowchart TB
  FCF["Free cash flow after interest and taxes"] --> Av["Cash available for debt repayment<br/>= beginning cash − minimum cash + FCF"]
  Av --> Md["Mandatory amortization<br/>e.g. 1% a year on term loan B"]
  Md --> Q{"Cash left after mandatory payments?"}
  Q -->|"surplus"| Sw["Optional repayment / cash sweep<br/>revolver first, then prepayable term loans"]
  Q -->|"shortfall"| Rv["Draw on the revolver up to its commitment"]
  Sw --> End["Ending balance per tranche"]
  Rv --> End
  End --> In["Interest = rate × average or beginning balance"]
  In -.->|"back to the income statement, circular if average"| FCF$$
    ),
    (
        'diag_working_capital_v1',
        'diag_working_capital',
        '1',
        'mermaid',
        $$flowchart LR
  Cash["Cash"] -->|"buy inventory"| Inv["Inventory<br/>days inventory outstanding, DIO"]
  Inv -->|"sell on credit"| AR["Accounts receivable<br/>days sales outstanding, DSO"]
  AR -->|"collect"| Cash
  AP["Accounts payable<br/>days payable outstanding, DPO"] -.->|"supplier credit delays cash out"| Cash
  CCC["Cash conversion cycle = DIO + DSO − DPO"]
  Rule["Operating NWC up → cash from operations down<br/>AR or inventory up uses cash, AP or deferred revenue up frees cash"]$$
    ),
    (
        'diag_merger_model_v1',
        'diag_merger_model',
        '1',
        'mermaid',
        $$flowchart TB
  Pr["Purchase price = offer price × target diluted shares<br/>+ refinanced target debt + fees"] --> SU["Sources and uses"]
  SU --> Ca["Cash on hand<br/>cost: forgone interest income"]
  SU --> ND["New debt<br/>cost: after-tax interest expense"]
  SU --> St["New acquirer stock<br/>cost: more shares, yield = 1 ÷ acquirer P/E"]
  Pr --> PPA["Purchase price allocation<br/>asset write-ups, then goodwill"]
  PPA --> DA["Extra D&A on written-up assets"]
  Cb["Acquirer net income + target net income"] --> NI["Pro forma net income"]
  Sy["After-tax synergies"] --> NI
  Ca --> NI
  ND --> NI
  DA --> NI
  St --> Sh["Pro forma shares"]
  NI --> EPS["Pro forma EPS vs acquirer standalone EPS"]
  Sh --> EPS
  EPS --> Out["Accretive or dilutive"]$$
    ),
    (
        'diag_returns_attribution_v1',
        'diag_returns_attribution',
        '1',
        'mermaid',
        $$flowchart LR
  En["Entry: EBITDA 100 × 10.0x = EV 1,000<br/>net debt 600, equity 400"] --> Ex["Exit: EBITDA 150 × 11.0x = EV 1,650<br/>net debt 300, equity 1,350"]
  Ex --> G["Equity gain 950, MOIC ≈ 3.4x"]
  G --> Gr["EBITDA growth: 50 × 10.0x = 500"]
  G --> Mu["Multiple expansion: 1.0x × 150 = 150"]
  G --> De["Deleveraging: 600 − 300 = 300"]$$
    ),
    (
        'diag_ddm_v1',
        'diag_ddm',
        '1',
        'mermaid',
        $$flowchart LR
  NI["Projected net income"] --> Cap["Retain enough to hit target CET1 / equity ratio<br/>as the balance sheet grows"]
  Cap --> Dv["Dividends = net income − required capital build"]
  Dv --> PVD["PV of dividends at cost of equity"]
  Dv --> TV["Terminal value = next-year dividend ÷ (Ke − g)<br/>or P/TBV, P/E exit multiple"]
  TV --> PVT["PV of terminal value at cost of equity"]
  PVD --> EqV["Equity value directly, no EV bridge"]
  PVT --> EqV
  EqV --> PS["÷ diluted shares = value per share"]
  Why["Why: debt and deposits are a bank's raw material,<br/>so value equity, not enterprise value"] -.-> EqV$$
    ),
    (
        'diag_football_field_v1',
        'diag_football_field',
        '1',
        'mermaid',
        $$flowchart TB
  subgraph FF["Implied share price ranges, $ per share"]
    direction TB
    W52["52-week trading range: 38 – 52"]
    TC["Trading comps: 40 – 55"]
    PT["Precedent transactions: 48 – 63"]
    DCF["DCF: 45 – 70"]
    LBO["LBO at 20–25% IRR: 36 – 50"]
  end
  FF --> Rec["Where ranges overlap guides the recommendation<br/>e.g. 48 – 55 vs current price 42"]$$
    ),
    (
        'diag_restructuring_waterfall_v1',
        'diag_restructuring_waterfall',
        '1',
        'mermaid',
        $$flowchart TB
  V["Distributable value, reorganised EV: 800"] --> Ad["Administrative and priority claims 50: paid in full"]
  Ad --> Se["Senior secured debt 500: paid in full, 250 value remains"]
  Se --> Un["Senior unsecured notes 400: receive 250, 62.5% recovery<br/>fulcrum security, usually takes the new equity"]
  Un --> Sb["Subordinated notes 150: 0% recovery"]
  Sb --> Eq["Existing equity: wiped out"]$$
    ),
    (
        'diag_pe_distribution_waterfall_v1',
        'diag_pe_distribution_waterfall',
        '1',
        'mermaid',
        $$flowchart TB
  D["Distributions from exits and recaps"] --> T1["1. Return of capital<br/>100% to LPs until contributed capital is returned"]
  T1 --> T2["2. Preferred return<br/>100% to LPs until an 8% annual hurdle"]
  T2 --> T3["3. GP catch-up<br/>mostly to the GP until it has 20% of profits"]
  T3 --> T4["4. Carried interest split<br/>80% LPs, 20% GP thereafter"]
  Fee["Management fee ≈ 1.5–2% of commitments a year<br/>funds the GP's operations, separate from carry"] -.-> D$$
    )
ON CONFLICT (diagram_id, version) DO UPDATE SET
    format = EXCLUDED.format,
    body = EXCLUDED.body;

INSERT INTO canonical.question_diagrams (question_id, diagram_id, relevance)
SELECT v.question_id, v.diagram_id, v.relevance
FROM (VALUES
    ('cq_027326f9e4e74d15', 'diag_accretion_dilution', 1.00),
    ('cq_118a4c5d57284599', 'diag_accretion_dilution', 0.50),
    ('cq_1fa7d3efefe8404e', 'diag_accretion_dilution', 0.50),
    ('cq_23104860d1224e84', 'diag_accretion_dilution', 1.00),
    ('cq_28aee31e189f4982', 'diag_accretion_dilution', 0.50),
    ('cq_29c9322df89f45d8', 'diag_accretion_dilution', 0.50),
    ('cq_31bbe094300a4329', 'diag_accretion_dilution', 0.50),
    ('cq_39e45ee94e2f4300', 'diag_accretion_dilution', 0.50),
    ('cq_442404194c834072', 'diag_accretion_dilution', 1.00),
    ('cq_46a39b01251046be', 'diag_accretion_dilution', 1.00),
    ('cq_487311bc7d564ad7', 'diag_accretion_dilution', 0.50),
    ('cq_48b8801e6a6044bb', 'diag_accretion_dilution', 0.50),
    ('cq_4e50b872e9494d01', 'diag_accretion_dilution', 0.50),
    ('cq_5fb9818e22294108', 'diag_accretion_dilution', 1.00),
    ('cq_62821424143243db', 'diag_accretion_dilution', 0.50),
    ('cq_62d1a9031aed41cc', 'diag_accretion_dilution', 0.50),
    ('cq_6bbe0c634b1144ca', 'diag_accretion_dilution', 1.00),
    ('cq_6e69da8378cc46d0', 'diag_accretion_dilution', 1.00),
    ('cq_6fdef2ea7f6243a4', 'diag_accretion_dilution', 0.85),
    ('cq_76069fa774d24ef6', 'diag_accretion_dilution', 0.95),
    ('cq_87154a13fcb64170', 'diag_accretion_dilution', 0.50),
    ('cq_8c0197e36de84db2', 'diag_accretion_dilution', 0.50),
    ('cq_8c81e67f2b11471d', 'diag_accretion_dilution', 0.80),
    ('cq_8fd6dec9ccc248d7', 'diag_accretion_dilution', 0.50),
    ('cq_9ad3a26cd88e4c75', 'diag_accretion_dilution', 0.50),
    ('cq_bb2c1e5588734394', 'diag_accretion_dilution', 1.00),
    ('cq_c0b3bf787dd443cf', 'diag_accretion_dilution', 1.00),
    ('cq_d372b36ccbba4b4d', 'diag_accretion_dilution', 1.00),
    ('cq_e22e28f4cd2642c2', 'diag_accretion_dilution', 0.80),
    ('cq_e7a95d10b400440c', 'diag_accretion_dilution', 1.00),
    ('cq_e7e5c39b974642c2', 'diag_accretion_dilution', 0.50),
    ('cq_e826eab821974705', 'diag_accretion_dilution', 0.50),
    ('cq_f1b3494c56dd40c8', 'diag_accretion_dilution', 0.50),
    ('cq_f2063ecaffef4d41', 'diag_accretion_dilution', 0.80),
    ('cq_f426d73a85ff4850', 'diag_accretion_dilution', 0.50),
    ('cq_f814997556c44ee4', 'diag_accretion_dilution', 0.50),
    ('cq_f8241edb00464789', 'diag_accretion_dilution', 0.50),
    ('cq_f98259b619824ecf', 'diag_accretion_dilution', 0.50),
    ('cq_0220996bda424750', 'diag_comps_precedents', 0.95),
    ('cq_065302ded3394e98', 'diag_comps_precedents', 0.50),
    ('cq_0bc3a8f6aec34891', 'diag_comps_precedents', 0.50),
    ('cq_0ed8c9f7a4ae4d14', 'diag_comps_precedents', 0.60),
    ('cq_15549d2fc9a04483', 'diag_comps_precedents', 0.90),
    ('cq_17d753fb32904f73', 'diag_comps_precedents', 0.50),
    ('cq_281a64f347a44380', 'diag_comps_precedents', 0.50),
    ('cq_281eee967e0a4a03', 'diag_comps_precedents', 0.60),
    ('cq_2827195a0ae241f1', 'diag_comps_precedents', 1.00),
    ('cq_29a6a19967234461', 'diag_comps_precedents', 0.50),
    ('cq_29fb1b768111452f', 'diag_comps_precedents', 0.50),
    ('cq_36b06d125c744dc5', 'diag_comps_precedents', 0.50),
    ('cq_442696f0eac84c46', 'diag_comps_precedents', 0.55),
    ('cq_465b1f33d4914874', 'diag_comps_precedents', 0.95),
    ('cq_4cb8d04837d64e81', 'diag_comps_precedents', 1.00),
    ('cq_4d88254017944cb1', 'diag_comps_precedents', 0.50),
    ('cq_5017daf3a5ca46b4', 'diag_comps_precedents', 0.60),
    ('cq_50b4f448a2c9438b', 'diag_comps_precedents', 0.60),
    ('cq_5a955926b69a4ff5', 'diag_comps_precedents', 0.50),
    ('cq_5c2e5cbb236642d2', 'diag_comps_precedents', 0.60),
    ('cq_63383f54fc6340a4', 'diag_comps_precedents', 0.60),
    ('cq_637cea43aead407a', 'diag_comps_precedents', 0.90),
    ('cq_6ada452a12d44d76', 'diag_comps_precedents', 0.50),
    ('cq_6d3def548a7f4b38', 'diag_comps_precedents', 0.60),
    ('cq_802b37c575eb4631', 'diag_comps_precedents', 0.60),
    ('cq_82cfeca372c34d0a', 'diag_comps_precedents', 0.55),
    ('cq_84d65ab0c9614e79', 'diag_comps_precedents', 0.90),
    ('cq_858f9b80b4334667', 'diag_comps_precedents', 0.60),
    ('cq_8f509c87423d43ee', 'diag_comps_precedents', 0.90),
    ('cq_91bce5ff306b422a', 'diag_comps_precedents', 1.00),
    ('cq_9334a0bdc37348f3', 'diag_comps_precedents', 0.55),
    ('cq_9472055101c34479', 'diag_comps_precedents', 0.55),
    ('cq_9504a2e322ec4529', 'diag_comps_precedents', 0.55),
    ('cq_957a1a5ad8bb421b', 'diag_comps_precedents', 0.50),
    ('cq_98ee7947a97c4c85', 'diag_comps_precedents', 0.90),
    ('cq_9d456291655f46b3', 'diag_comps_precedents', 0.50),
    ('cq_9dc9da9dde0949d3', 'diag_comps_precedents', 0.50),
    ('cq_a019037769ce4b94', 'diag_comps_precedents', 0.90),
    ('cq_a06ed529e9784dbd', 'diag_comps_precedents', 0.55),
    ('cq_aa1846da3f964f4d', 'diag_comps_precedents', 0.50),
    ('cq_aa71d1b1619f4627', 'diag_comps_precedents', 0.50),
    ('cq_bd2ad243fd424d43', 'diag_comps_precedents', 0.50),
    ('cq_caf5a47cdde04778', 'diag_comps_precedents', 0.50),
    ('cq_cf4265fa6861465a', 'diag_comps_precedents', 0.60),
    ('cq_e97e4e545cac465b', 'diag_comps_precedents', 0.50),
    ('cq_f06907cf13db44ab', 'diag_comps_precedents', 0.60),
    ('cq_f9a00579c6f24f44', 'diag_comps_precedents', 0.55),
    ('cq_feb4ddab223041e3', 'diag_comps_precedents', 0.55),
    ('cq_ff508b642c054bde', 'diag_comps_precedents', 0.50),
    ('cq_0051b6ee2aee4244', 'diag_dcf_wacc', 0.90),
    ('cq_065302ded3394e98', 'diag_dcf_wacc', 0.50),
    ('cq_0bc3a8f6aec34891', 'diag_dcf_wacc', 0.50),
    ('cq_14f0acda1fd344cb', 'diag_dcf_wacc', 0.90),
    ('cq_17d753fb32904f73', 'diag_dcf_wacc', 0.50),
    ('cq_1990bf98f34d4d15', 'diag_dcf_wacc', 0.75),
    ('cq_1a11f32723f045c5', 'diag_dcf_wacc', 0.90),
    ('cq_1b778691996445cc', 'diag_dcf_wacc', 0.90),
    ('cq_1d8137bf26a74f84', 'diag_dcf_wacc', 0.95),
    ('cq_20620db1939a4773', 'diag_dcf_wacc', 0.90),
    ('cq_25a4f6848fa24270', 'diag_dcf_wacc', 0.95),
    ('cq_281a64f347a44380', 'diag_dcf_wacc', 0.50),
    ('cq_281eee967e0a4a03', 'diag_dcf_wacc', 0.75),
    ('cq_29a6a19967234461', 'diag_dcf_wacc', 0.50),
    ('cq_29fb1b768111452f', 'diag_dcf_wacc', 0.50),
    ('cq_2b6abab9a11d43a3', 'diag_dcf_wacc', 0.95),
    ('cq_2fa52b2b06804f46', 'diag_dcf_wacc', 0.90),
    ('cq_3436925543da4a41', 'diag_dcf_wacc', 0.90),
    ('cq_36b06d125c744dc5', 'diag_dcf_wacc', 0.50),
    ('cq_3b84b0d0b2674433', 'diag_dcf_wacc', 0.70),
    ('cq_4077dbb80c224c6d', 'diag_dcf_wacc', 0.90),
    ('cq_4d88254017944cb1', 'diag_dcf_wacc', 0.50),
    ('cq_584236f4794042f7', 'diag_dcf_wacc', 0.95),
    ('cq_58bf47a691df4b2b', 'diag_dcf_wacc', 0.95),
    ('cq_5a955926b69a4ff5', 'diag_dcf_wacc', 0.50),
    ('cq_6104bd5bb2294cb1', 'diag_dcf_wacc', 0.75),
    ('cq_630a9ff5d05c4ee6', 'diag_dcf_wacc', 0.75),
    ('cq_6ada452a12d44d76', 'diag_dcf_wacc', 0.50),
    ('cq_704b3332dc224084', 'diag_dcf_wacc', 0.75),
    ('cq_71a764c3f71741ff', 'diag_dcf_wacc', 0.90),
    ('cq_7d6d75264c3f4195', 'diag_dcf_wacc', 0.95),
    ('cq_802b37c575eb4631', 'diag_dcf_wacc', 0.75),
    ('cq_830429c5e4774197', 'diag_dcf_wacc', 0.90),
    ('cq_90b70b52a63c4cd2', 'diag_dcf_wacc', 0.90),
    ('cq_92e553376cf6433a', 'diag_dcf_wacc', 0.90),
    ('cq_9552b878ebcb4e69', 'diag_dcf_wacc', 0.90),
    ('cq_957a1a5ad8bb421b', 'diag_dcf_wacc', 0.50),
    ('cq_96dd43b381d74166', 'diag_dcf_wacc', 0.90),
    ('cq_99e2dd9d186f447e', 'diag_dcf_wacc', 0.90),
    ('cq_9d456291655f46b3', 'diag_dcf_wacc', 0.50),
    ('cq_9dc9da9dde0949d3', 'diag_dcf_wacc', 0.50),
    ('cq_9f0737b1e2d0463e', 'diag_dcf_wacc', 0.90),
    ('cq_a13c8d856a464a77', 'diag_dcf_wacc', 0.95),
    ('cq_a84bb87bc8cb4783', 'diag_dcf_wacc', 0.95),
    ('cq_a8bae917c43242a3', 'diag_dcf_wacc', 0.90),
    ('cq_aa1846da3f964f4d', 'diag_dcf_wacc', 0.50),
    ('cq_aa71d1b1619f4627', 'diag_dcf_wacc', 0.50),
    ('cq_afa4d293f1af4980', 'diag_dcf_wacc', 0.70),
    ('cq_b0ed4eeaba614b8b', 'diag_dcf_wacc', 0.75),
    ('cq_b1b65546c5624d38', 'diag_dcf_wacc', 0.95),
    ('cq_bd2ad243fd424d43', 'diag_dcf_wacc', 0.50),
    ('cq_bef1b0b7e2d94d04', 'diag_dcf_wacc', 0.80),
    ('cq_c7e6a2e30c27443d', 'diag_dcf_wacc', 0.90),
    ('cq_caf5a47cdde04778', 'diag_dcf_wacc', 0.50),
    ('cq_cdb514424b7d4ae8', 'diag_dcf_wacc', 0.70),
    ('cq_cdd7855a21314692', 'diag_dcf_wacc', 0.90),
    ('cq_d5c2dc215d83443f', 'diag_dcf_wacc', 0.90),
    ('cq_e3896996740d4569', 'diag_dcf_wacc', 0.95),
    ('cq_e972e77e6d074476', 'diag_dcf_wacc', 0.90),
    ('cq_e97e4e545cac465b', 'diag_dcf_wacc', 0.50),
    ('cq_ff508b642c054bde', 'diag_dcf_wacc', 0.50),
    ('cq_00a1635dbfc14545', 'diag_ddm', 0.80),
    ('cq_21ab1c196db34188', 'diag_ddm', 0.85),
    ('cq_000970a3f9f745d2', 'diag_debt_schedule', 0.70),
    ('cq_0195ce6a368d4127', 'diag_debt_schedule', 0.95),
    ('cq_04c45f0180754a77', 'diag_debt_schedule', 0.65),
    ('cq_09502737b5ef4468', 'diag_debt_schedule', 0.80),
    ('cq_111a2162284c4d95', 'diag_debt_schedule', 0.50),
    ('cq_16c4bac0b4d64c5b', 'diag_debt_schedule', 0.50),
    ('cq_19d04ba39a864240', 'diag_debt_schedule', 0.50),
    ('cq_24281bd5942d41bb', 'diag_debt_schedule', 0.50),
    ('cq_2c36063d416e405d', 'diag_debt_schedule', 0.50),
    ('cq_2ebcbdebfa0c4366', 'diag_debt_schedule', 0.50),
    ('cq_3c72153afbc946b3', 'diag_debt_schedule', 0.70),
    ('cq_528ffdb15fa84ae6', 'diag_debt_schedule', 0.95),
    ('cq_5f8a93e011af4127', 'diag_debt_schedule', 0.65),
    ('cq_67012a2cfaf346a0', 'diag_debt_schedule', 0.50),
    ('cq_70607bdcedee4ff3', 'diag_debt_schedule', 0.50),
    ('cq_7574e2ee51d2407f', 'diag_debt_schedule', 0.60),
    ('cq_80505d5a574945e0', 'diag_debt_schedule', 0.65),
    ('cq_8dc827047a914e8f', 'diag_debt_schedule', 0.50),
    ('cq_983ed854ac6d45a5', 'diag_debt_schedule', 0.80),
    ('cq_99a2bb2101334835', 'diag_debt_schedule', 0.60),
    ('cq_a37fd9e885ac4fa9', 'diag_debt_schedule', 0.65),
    ('cq_a710c63e4e344f83', 'diag_debt_schedule', 0.50),
    ('cq_b64f42b204b24ebc', 'diag_debt_schedule', 0.50),
    ('cq_b7acb1b0a4a649ea', 'diag_debt_schedule', 0.65),
    ('cq_b8487baf80f14a51', 'diag_debt_schedule', 0.80),
    ('cq_b8d612b3f1174cc4', 'diag_debt_schedule', 0.50),
    ('cq_cf6849820f8145ef', 'diag_debt_schedule', 0.65),
    ('cq_d084e736ecfb49f8', 'diag_debt_schedule', 0.60),
    ('cq_ddd2fe3df4134be6', 'diag_debt_schedule', 0.65),
    ('cq_e8d8a27c33784400', 'diag_debt_schedule', 0.50),
    ('cq_f43b13706a8d4917', 'diag_debt_schedule', 0.50),
    ('cq_f5e196d8c20142f3', 'diag_debt_schedule', 0.60),
    ('cq_f999424a728d4551', 'diag_debt_schedule', 0.50),
    ('cq_084fb1f6479a4b28', 'diag_ev_bridge', 0.50),
    ('cq_16283e97421d4821', 'diag_ev_bridge', 0.90),
    ('cq_16946646d74d4efc', 'diag_ev_bridge', 0.95),
    ('cq_187fa95cce7b408d', 'diag_ev_bridge', 0.95),
    ('cq_1c3adf726d644ee0', 'diag_ev_bridge', 0.70),
    ('cq_281eee967e0a4a03', 'diag_ev_bridge', 0.95),
    ('cq_2a195733afe14235', 'diag_ev_bridge', 0.70),
    ('cq_32daa6c06e3a46ad', 'diag_ev_bridge', 0.95),
    ('cq_40b72295f4ed403c', 'diag_ev_bridge', 0.50),
    ('cq_42ecb89c5dec425f', 'diag_ev_bridge', 1.00),
    ('cq_47a13c5fa47d4272', 'diag_ev_bridge', 0.95),
    ('cq_5017daf3a5ca46b4', 'diag_ev_bridge', 0.95),
    ('cq_5c123fab555c4855', 'diag_ev_bridge', 0.90),
    ('cq_617fc6eaff9a441a', 'diag_ev_bridge', 0.90),
    ('cq_6b41bb93a2c24040', 'diag_ev_bridge', 0.95),
    ('cq_6b8932f1b2684545', 'diag_ev_bridge', 0.70),
    ('cq_6d3def548a7f4b38', 'diag_ev_bridge', 0.95),
    ('cq_785ce401ed804444', 'diag_ev_bridge', 0.65),
    ('cq_7f3b290cb078425d', 'diag_ev_bridge', 0.70),
    ('cq_8a75fe6712ca4fe3', 'diag_ev_bridge', 0.90),
    ('cq_96dd43b381d74166', 'diag_ev_bridge', 0.90),
    ('cq_9dc7c62ff03d4572', 'diag_ev_bridge', 0.90),
    ('cq_a38f594a71df47da', 'diag_ev_bridge', 0.70),
    ('cq_af6e3706687048bd', 'diag_ev_bridge', 0.60),
    ('cq_b0e29150b0fd4631', 'diag_ev_bridge', 0.50),
    ('cq_c28a2863ec0e4152', 'diag_ev_bridge', 0.90),
    ('cq_c4ea125991dc4975', 'diag_ev_bridge', 0.50),
    ('cq_c8c5853db63149c6', 'diag_ev_bridge', 0.90),
    ('cq_ccb203dbbac0404c', 'diag_ev_bridge', 0.95),
    ('cq_d3cb5b15d30a4d36', 'diag_ev_bridge', 0.95),
    ('cq_e05fef96bfae4425', 'diag_ev_bridge', 0.90),
    ('cq_442696f0eac84c46', 'diag_football_field', 0.80),
    ('cq_82cfeca372c34d0a', 'diag_football_field', 0.60),
    ('cq_9334a0bdc37348f3', 'diag_football_field', 0.60),
    ('cq_9472055101c34479', 'diag_football_field', 0.60),
    ('cq_9504a2e322ec4529', 'diag_football_field', 0.60),
    ('cq_a06ed529e9784dbd', 'diag_football_field', 0.95),
    ('cq_f9a00579c6f24f44', 'diag_football_field', 0.95),
    ('cq_feb4ddab223041e3', 'diag_football_field', 0.80),
    ('cq_000970a3f9f745d2', 'diag_lbo_sources_uses', 0.75),
    ('cq_0195ce6a368d4127', 'diag_lbo_sources_uses', 0.55),
    ('cq_0e7fbe121f71483a', 'diag_lbo_sources_uses', 0.55),
    ('cq_3279968442654676', 'diag_lbo_sources_uses', 0.55),
    ('cq_367c383e66594921', 'diag_lbo_sources_uses', 0.90),
    ('cq_38a231fb832e4a61', 'diag_lbo_sources_uses', 0.55),
    ('cq_395837d575dc443d', 'diag_lbo_sources_uses', 0.55),
    ('cq_3c72153afbc946b3', 'diag_lbo_sources_uses', 0.55),
    ('cq_456d5ed63c554e42', 'diag_lbo_sources_uses', 0.55),
    ('cq_528ffdb15fa84ae6', 'diag_lbo_sources_uses', 0.55),
    ('cq_5a0d575fc0c4498c', 'diag_lbo_sources_uses', 0.55),
    ('cq_5b8ae12a8f3c4e0a', 'diag_lbo_sources_uses', 0.70),
    ('cq_6b9dd095581940c3', 'diag_lbo_sources_uses', 0.55),
    ('cq_7574e2ee51d2407f', 'diag_lbo_sources_uses', 0.55),
    ('cq_7847cf7c3d4442d1', 'diag_lbo_sources_uses', 0.70),
    ('cq_7c29d259b4004a54', 'diag_lbo_sources_uses', 0.55),
    ('cq_7ef604ebf0254239', 'diag_lbo_sources_uses', 0.55),
    ('cq_817ae10de3fe49c1', 'diag_lbo_sources_uses', 0.50),
    ('cq_848e98a343c14dc3', 'diag_lbo_sources_uses', 0.55),
    ('cq_8eb0105103784087', 'diag_lbo_sources_uses', 0.55),
    ('cq_90a9210d6c464579', 'diag_lbo_sources_uses', 0.55),
    ('cq_90b70b52a63c4cd2', 'diag_lbo_sources_uses', 0.55),
    ('cq_9779bfc619254462', 'diag_lbo_sources_uses', 0.55),
    ('cq_9f7f7b3a2b6d4761', 'diag_lbo_sources_uses', 0.55),
    ('cq_a0c3b602d5d64e68', 'diag_lbo_sources_uses', 0.55),
    ('cq_a2a93d7610494d4a', 'diag_lbo_sources_uses', 0.55),
    ('cq_a61d97d82d294d52', 'diag_lbo_sources_uses', 0.55),
    ('cq_a7f1bde8d295493f', 'diag_lbo_sources_uses', 0.65),
    ('cq_aff6fd944e474755', 'diag_lbo_sources_uses', 0.55),
    ('cq_bf5bf62eb14c4a85', 'diag_lbo_sources_uses', 0.55),
    ('cq_c8183b1f88294c25', 'diag_lbo_sources_uses', 0.55),
    ('cq_cb6cfd3c79e54cdf', 'diag_lbo_sources_uses', 0.55),
    ('cq_d42e771c048940a7', 'diag_lbo_sources_uses', 0.55),
    ('cq_d5c2dc215d83443f', 'diag_lbo_sources_uses', 0.55),
    ('cq_e6c2dab85ec64b0d', 'diag_lbo_sources_uses', 0.55),
    ('cq_e91ac5aff6c0420a', 'diag_lbo_sources_uses', 0.55),
    ('cq_ef1014400e684464', 'diag_lbo_sources_uses', 0.55),
    ('cq_f75f4ca2412a45bc', 'diag_lbo_sources_uses', 0.55),
    ('cq_118a4c5d57284599', 'diag_merger_model', 0.50),
    ('cq_1375884d460a4728', 'diag_merger_model', 0.95),
    ('cq_196bfece926c4771', 'diag_merger_model', 0.70),
    ('cq_1fa7d3efefe8404e', 'diag_merger_model', 0.50),
    ('cq_28aee31e189f4982', 'diag_merger_model', 0.50),
    ('cq_28e19f6b22c34cd0', 'diag_merger_model', 0.80),
    ('cq_2956125a0a044772', 'diag_merger_model', 0.95),
    ('cq_29c9322df89f45d8', 'diag_merger_model', 0.50),
    ('cq_31bbe094300a4329', 'diag_merger_model', 0.50),
    ('cq_39e45ee94e2f4300', 'diag_merger_model', 0.50),
    ('cq_480b08d384c84b82', 'diag_merger_model', 0.70),
    ('cq_487311bc7d564ad7', 'diag_merger_model', 0.50),
    ('cq_48b8801e6a6044bb', 'diag_merger_model', 0.50),
    ('cq_4d7ed5a72dc8404f', 'diag_merger_model', 0.70),
    ('cq_4e50b872e9494d01', 'diag_merger_model', 0.50),
    ('cq_592c9172d4814ad1', 'diag_merger_model', 0.70),
    ('cq_5e478a31fba944ae', 'diag_merger_model', 0.70),
    ('cq_62821424143243db', 'diag_merger_model', 0.50),
    ('cq_62d1a9031aed41cc', 'diag_merger_model', 0.50),
    ('cq_6fdef2ea7f6243a4', 'diag_merger_model', 0.70),
    ('cq_72e8ead8bc374bc4', 'diag_merger_model', 0.95),
    ('cq_87154a13fcb64170', 'diag_merger_model', 0.50),
    ('cq_8c0197e36de84db2', 'diag_merger_model', 0.50),
    ('cq_8c81e67f2b11471d', 'diag_merger_model', 0.95),
    ('cq_8fd6dec9ccc248d7', 'diag_merger_model', 0.50),
    ('cq_9ad3a26cd88e4c75', 'diag_merger_model', 0.50),
    ('cq_9f5ac0cd3d38479c', 'diag_merger_model', 0.70),
    ('cq_a07d7dc8e24d40c5', 'diag_merger_model', 0.70),
    ('cq_a1771eb474b144ce', 'diag_merger_model', 0.70),
    ('cq_a9c37932791d4236', 'diag_merger_model', 0.70),
    ('cq_b4702098ba7846dc', 'diag_merger_model', 0.95),
    ('cq_cd708c80b0d54d0b', 'diag_merger_model', 0.95),
    ('cq_d6d959af4e604345', 'diag_merger_model', 0.70),
    ('cq_e22e28f4cd2642c2', 'diag_merger_model', 0.70),
    ('cq_e7e5c39b974642c2', 'diag_merger_model', 0.50),
    ('cq_e826eab821974705', 'diag_merger_model', 0.50),
    ('cq_f1b3494c56dd40c8', 'diag_merger_model', 0.50),
    ('cq_f2133cc4655f4241', 'diag_merger_model', 0.80),
    ('cq_f426d73a85ff4850', 'diag_merger_model', 0.50),
    ('cq_f45161874f3947f0', 'diag_merger_model', 0.95),
    ('cq_f6941c5fe0eb4c8c', 'diag_merger_model', 0.95),
    ('cq_f814997556c44ee4', 'diag_merger_model', 0.50),
    ('cq_f8241edb00464789', 'diag_merger_model', 0.50),
    ('cq_f98259b619824ecf', 'diag_merger_model', 0.50),
    ('cq_ff561da3731b44e9', 'diag_merger_model', 0.85),
    ('cq_1ac14e4506694dc2', 'diag_moic_irr', 0.90),
    ('cq_1e567a8fcaa645a7', 'diag_moic_irr', 0.90),
    ('cq_415a984b063944a6', 'diag_moic_irr', 1.00),
    ('cq_7c29d259b4004a54', 'diag_moic_irr', 0.90),
    ('cq_95bbf5673ab7428d', 'diag_moic_irr', 0.60),
    ('cq_a0c3b602d5d64e68', 'diag_moic_irr', 1.00),
    ('cq_a1a3050dcdcd4998', 'diag_moic_irr', 1.00),
    ('cq_b8487baf80f14a51', 'diag_moic_irr', 0.90),
    ('cq_b9f20ed1f54a4d5e', 'diag_moic_irr', 1.00),
    ('cq_1e567a8fcaa645a7', 'diag_paper_lbo_returns', 0.75),
    ('cq_38a231fb832e4a61', 'diag_paper_lbo_returns', 0.75),
    ('cq_817ae10de3fe49c1', 'diag_paper_lbo_returns', 0.50),
    ('cq_95bbf5673ab7428d', 'diag_paper_lbo_returns', 0.80),
    ('cq_a0c3b602d5d64e68', 'diag_paper_lbo_returns', 0.95),
    ('cq_aff6fd944e474755', 'diag_paper_lbo_returns', 0.80),
    ('cq_0fa258ed5a9040a5', 'diag_pe_distribution_waterfall', 0.55),
    ('cq_1ac14e4506694dc2', 'diag_pe_distribution_waterfall', 0.90),
    ('cq_26c4812a09814877', 'diag_pe_distribution_waterfall', 0.55),
    ('cq_2d3a9f2c7c184c55', 'diag_pe_distribution_waterfall', 0.55),
    ('cq_395837d575dc443d', 'diag_pe_distribution_waterfall', 0.55),
    ('cq_415a984b063944a6', 'diag_pe_distribution_waterfall', 0.55),
    ('cq_834bb6b784844e9c', 'diag_pe_distribution_waterfall', 0.55),
    ('cq_02850f4f3b334148', 'diag_restructuring_waterfall', 0.65),
    ('cq_055824f6794241a3', 'diag_restructuring_waterfall', 0.50),
    ('cq_2997bd4cfc8c4918', 'diag_restructuring_waterfall', 0.50),
    ('cq_2e48111357754f1f', 'diag_restructuring_waterfall', 0.50),
    ('cq_314764dfa22b4b6e', 'diag_restructuring_waterfall', 0.50),
    ('cq_317482e279b34a4a', 'diag_restructuring_waterfall', 0.50),
    ('cq_372b7963549c4516', 'diag_restructuring_waterfall', 0.70),
    ('cq_3cf64d475a3e4bb4', 'diag_restructuring_waterfall', 0.50),
    ('cq_41ba7f8c766d420c', 'diag_restructuring_waterfall', 0.50),
    ('cq_4a6b1f732dd041d9', 'diag_restructuring_waterfall', 0.95),
    ('cq_5722c6555ed64ca6', 'diag_restructuring_waterfall', 0.95),
    ('cq_5e07623a41c143d1', 'diag_restructuring_waterfall', 0.70),
    ('cq_634399de75f54d28', 'diag_restructuring_waterfall', 0.50),
    ('cq_6c551b5f88444c01', 'diag_restructuring_waterfall', 0.70),
    ('cq_6d5763719a5c43c6', 'diag_restructuring_waterfall', 0.50),
    ('cq_73b896690a3c437a', 'diag_restructuring_waterfall', 0.50),
    ('cq_75f39181ea83484a', 'diag_restructuring_waterfall', 0.50),
    ('cq_7b497b1a7f7a407b', 'diag_restructuring_waterfall', 0.50),
    ('cq_7dc4df4d251d4f2e', 'diag_restructuring_waterfall', 0.50),
    ('cq_8b0de4405b2d479d', 'diag_restructuring_waterfall', 0.85),
    ('cq_8bb7af522576493d', 'diag_restructuring_waterfall', 0.50),
    ('cq_8cd07aef990d43bf', 'diag_restructuring_waterfall', 0.50),
    ('cq_8f81409da8dc4269', 'diag_restructuring_waterfall', 0.65),
    ('cq_9478cd3cd94447b0', 'diag_restructuring_waterfall', 0.65),
    ('cq_98b8d28463314a4f', 'diag_restructuring_waterfall', 1.00),
    ('cq_9d93eba7e5d34cd7', 'diag_restructuring_waterfall', 0.70),
    ('cq_ab64239bbf794790', 'diag_restructuring_waterfall', 0.70),
    ('cq_ad1f6558dc1d44b8', 'diag_restructuring_waterfall', 0.50),
    ('cq_ad2f66e24374432a', 'diag_restructuring_waterfall', 0.50),
    ('cq_b761e5b4146d4f2f', 'diag_restructuring_waterfall', 0.50),
    ('cq_b90abd24cb7f486f', 'diag_restructuring_waterfall', 0.70),
    ('cq_bc964fdd4b954f2e', 'diag_restructuring_waterfall', 0.50),
    ('cq_c099dcbaaca14af5', 'diag_restructuring_waterfall', 0.70),
    ('cq_c5abd1766cbc4ee9', 'diag_restructuring_waterfall', 0.70),
    ('cq_c8926e97da924dc2', 'diag_restructuring_waterfall', 0.50),
    ('cq_cbf2bcb6ca0f4a41', 'diag_restructuring_waterfall', 0.50),
    ('cq_d441cb9671b545ae', 'diag_restructuring_waterfall', 0.50),
    ('cq_db2d85e94757467e', 'diag_restructuring_waterfall', 0.50),
    ('cq_e88a30ec60144131', 'diag_restructuring_waterfall', 0.70),
    ('cq_edd956604ef84bff', 'diag_restructuring_waterfall', 0.50),
    ('cq_eebce9ab8df242f7', 'diag_restructuring_waterfall', 0.50),
    ('cq_ef88d00211d14a81', 'diag_restructuring_waterfall', 0.75),
    ('cq_01e7c5d426fa4c37', 'diag_returns_attribution', 0.50),
    ('cq_268b62c80f9c441d', 'diag_returns_attribution', 0.90),
    ('cq_298a889c9e4e47f6', 'diag_returns_attribution', 0.50),
    ('cq_36dc3ebdc5b84439', 'diag_returns_attribution', 0.50),
    ('cq_407edb5275c34e71', 'diag_returns_attribution', 0.50),
    ('cq_4183f81f841048f3', 'diag_returns_attribution', 0.95),
    ('cq_4daa7706f0944283', 'diag_returns_attribution', 0.50),
    ('cq_4ec6e43e30794fa3', 'diag_returns_attribution', 0.50),
    ('cq_542ebe69ac42419a', 'diag_returns_attribution', 0.50),
    ('cq_5904ce82111b41bc', 'diag_returns_attribution', 0.50),
    ('cq_5e5c379e54ad4a0e', 'diag_returns_attribution', 0.90),
    ('cq_68dd27bb315149a5', 'diag_returns_attribution', 0.50),
    ('cq_722c14e4fa504656', 'diag_returns_attribution', 0.50),
    ('cq_7af3be5110ec46d7', 'diag_returns_attribution', 0.50),
    ('cq_8042787314c04cad', 'diag_returns_attribution', 0.50),
    ('cq_813beb758c0b4a9d', 'diag_returns_attribution', 0.50),
    ('cq_95bbf5673ab7428d', 'diag_returns_attribution', 0.75),
    ('cq_9f7f7b3a2b6d4761', 'diag_returns_attribution', 0.90),
    ('cq_b0f946c778374adb', 'diag_returns_attribution', 0.50),
    ('cq_bd52df5c579d4040', 'diag_returns_attribution', 0.90),
    ('cq_d323c21387ba4e92', 'diag_returns_attribution', 0.50),
    ('cq_fef2bec2db7f4e89', 'diag_returns_attribution', 0.50),
    ('cq_10950b124a0648ad', 'diag_three_statement', 0.50),
    ('cq_13a6e32c14c94fa1', 'diag_three_statement', 0.95),
    ('cq_15099edc274d49b1', 'diag_three_statement', 0.95),
    ('cq_1990bf98f34d4d15', 'diag_three_statement', 0.60),
    ('cq_1b2ce929a7d140fe', 'diag_three_statement', 0.50),
    ('cq_1fde6871fd744ec2', 'diag_three_statement', 0.50),
    ('cq_23104860d1224e84', 'diag_three_statement', 0.95),
    ('cq_26d111dea711471a', 'diag_three_statement', 0.95),
    ('cq_2e232a58d0b4442f', 'diag_three_statement', 0.95),
    ('cq_2e8a4ce2324d4638', 'diag_three_statement', 0.50),
    ('cq_319c32cbe6954479', 'diag_three_statement', 0.50),
    ('cq_395837d575dc443d', 'diag_three_statement', 0.95),
    ('cq_459c8bd6a9514e7f', 'diag_three_statement', 0.50),
    ('cq_48ce60822518466e', 'diag_three_statement', 0.50),
    ('cq_5a6d5eb9e4684673', 'diag_three_statement', 0.50),
    ('cq_63504fd1349e41a3', 'diag_three_statement', 1.00),
    ('cq_66d629bc5c064957', 'diag_three_statement', 0.50),
    ('cq_68b428ba6b9d444f', 'diag_three_statement', 0.50),
    ('cq_699ec9fe28eb4027', 'diag_three_statement', 0.50),
    ('cq_6b7b6ee3a9bf49ab', 'diag_three_statement', 0.50),
    ('cq_6dc940852cdf4d56', 'diag_three_statement', 0.50),
    ('cq_74ba880e08364053', 'diag_three_statement', 0.50),
    ('cq_7eb46b60e55140cb', 'diag_three_statement', 0.50),
    ('cq_7f36d6b4d27a4deb', 'diag_three_statement', 0.50),
    ('cq_818591855be64455', 'diag_three_statement', 0.95),
    ('cq_823fcf04cf664152', 'diag_three_statement', 0.95),
    ('cq_825afa2d5cb04352', 'diag_three_statement', 0.95),
    ('cq_842e2a09b3294165', 'diag_three_statement', 0.95),
    ('cq_8788fe1a6dc9450e', 'diag_three_statement', 0.95),
    ('cq_8a366e3393b64915', 'diag_three_statement', 0.50),
    ('cq_95f257b1cc25442f', 'diag_three_statement', 0.50),
    ('cq_9779bfc619254462', 'diag_three_statement', 0.95),
    ('cq_a829bc3dea9044ed', 'diag_three_statement', 0.50),
    ('cq_ab78f4bb0e974d21', 'diag_three_statement', 0.50),
    ('cq_add7db6348ab468a', 'diag_three_statement', 0.50),
    ('cq_b2a52ee6a34342d2', 'diag_three_statement', 0.50),
    ('cq_c4c3acddbefa4fea', 'diag_three_statement', 0.95),
    ('cq_c9216f09ff614e58', 'diag_three_statement', 0.50),
    ('cq_cf0c497b90d54299', 'diag_three_statement', 0.95),
    ('cq_d463d28b141e43f1', 'diag_three_statement', 0.50),
    ('cq_d5c6df306ee1432e', 'diag_three_statement', 0.60),
    ('cq_da1dfabaee9543ed', 'diag_three_statement', 0.50),
    ('cq_ed0f423b523c4043', 'diag_three_statement', 0.50),
    ('cq_f12a05458b2a4e0b', 'diag_three_statement', 1.00),
    ('cq_f19ef9bf53304647', 'diag_three_statement', 0.95),
    ('cq_f605143baab8421d', 'diag_three_statement', 0.50),
    ('cq_f716dc4823f34263', 'diag_three_statement', 0.50),
    ('cq_f721ce19db65411b', 'diag_three_statement', 0.50),
    ('cq_0b2a4cdf26d04ec0', 'diag_three_statement_linkages', 0.65),
    ('cq_13a6e32c14c94fa1', 'diag_three_statement_linkages', 0.85),
    ('cq_15099edc274d49b1', 'diag_three_statement_linkages', 0.85),
    ('cq_1f3979ed0fb24cf4', 'diag_three_statement_linkages', 0.70),
    ('cq_23104860d1224e84', 'diag_three_statement_linkages', 0.85),
    ('cq_26d111dea711471a', 'diag_three_statement_linkages', 0.85),
    ('cq_2e232a58d0b4442f', 'diag_three_statement_linkages', 0.90),
    ('cq_44a2cdbcdf34411e', 'diag_three_statement_linkages', 0.55),
    ('cq_516b5dc422ef4aa9', 'diag_three_statement_linkages', 0.65),
    ('cq_63383f54fc6340a4', 'diag_three_statement_linkages', 0.65),
    ('cq_63504fd1349e41a3', 'diag_three_statement_linkages', 0.85),
    ('cq_6a32559edd124f4c', 'diag_three_statement_linkages', 0.55),
    ('cq_6e29aaf01dba4326', 'diag_three_statement_linkages', 0.60),
    ('cq_6ee4e8fdb74348ef', 'diag_three_statement_linkages', 0.55),
    ('cq_6f524f3351104f10', 'diag_three_statement_linkages', 0.75),
    ('cq_704b3332dc224084', 'diag_three_statement_linkages', 0.70),
    ('cq_818591855be64455', 'diag_three_statement_linkages', 0.90),
    ('cq_823fcf04cf664152', 'diag_three_statement_linkages', 0.85),
    ('cq_825afa2d5cb04352', 'diag_three_statement_linkages', 0.85),
    ('cq_842e2a09b3294165', 'diag_three_statement_linkages', 0.85),
    ('cq_8788fe1a6dc9450e', 'diag_three_statement_linkages', 0.85),
    ('cq_b1d96f6d7e2b447a', 'diag_three_statement_linkages', 0.55),
    ('cq_c4c3acddbefa4fea', 'diag_three_statement_linkages', 0.90),
    ('cq_cf0c497b90d54299', 'diag_three_statement_linkages', 0.85),
    ('cq_d5c6df306ee1432e', 'diag_three_statement_linkages', 0.65),
    ('cq_ef6feb8a1d9b44a6', 'diag_three_statement_linkages', 0.55),
    ('cq_f12a05458b2a4e0b', 'diag_three_statement_linkages', 0.90),
    ('cq_f19ef9bf53304647', 'diag_three_statement_linkages', 0.85),
    ('cq_fbc5552112444919', 'diag_three_statement_linkages', 0.75),
    ('cq_04d3336e757b4c09', 'diag_wacc_build', 1.00),
    ('cq_0df49d6e682f420d', 'diag_wacc_build', 0.95),
    ('cq_144739edafb9417d', 'diag_wacc_build', 0.90),
    ('cq_1b70b143206041c3', 'diag_wacc_build', 0.95),
    ('cq_3e9870db6dac494a', 'diag_wacc_build', 0.90),
    ('cq_667eaff09bdb443f', 'diag_wacc_build', 0.85),
    ('cq_67f4db3705834718', 'diag_wacc_build', 0.95),
    ('cq_6d48a91428b344b9', 'diag_wacc_build', 0.80),
    ('cq_96af2223dc774620', 'diag_wacc_build', 0.90),
    ('cq_9f9afa71337b4f27', 'diag_wacc_build', 1.00),
    ('cq_a22e06dc12d24290', 'diag_wacc_build', 0.95),
    ('cq_bd54d7903bdb46ef', 'diag_wacc_build', 0.85),
    ('cq_e9a215d4c2ff489f', 'diag_wacc_build', 0.95),
    ('cq_eb9b7744a8814fd4', 'diag_wacc_build', 0.90),
    ('cq_f73968b693874af0', 'diag_wacc_build', 0.95),
    ('cq_006f605c21ee4e84', 'diag_working_capital', 0.65),
    ('cq_0d63a50f2a924d87', 'diag_working_capital', 0.70),
    ('cq_13a6e32c14c94fa1', 'diag_working_capital', 0.70),
    ('cq_1b778691996445cc', 'diag_working_capital', 0.95),
    ('cq_1e88792d7d2249a1', 'diag_working_capital', 0.50),
    ('cq_20ed7451055f40e6', 'diag_working_capital', 0.70),
    ('cq_3119bcd91adb40da', 'diag_working_capital', 0.50),
    ('cq_3a4a719580654e34', 'diag_working_capital', 0.80),
    ('cq_3cbb3ee157cf4a70', 'diag_working_capital', 0.75),
    ('cq_4d057d34ba8e402e', 'diag_working_capital', 0.95),
    ('cq_5a16226fad3a49dd', 'diag_working_capital', 0.70),
    ('cq_5f8a93e011af4127', 'diag_working_capital', 0.95),
    ('cq_6104bd5bb2294cb1', 'diag_working_capital', 0.70),
    ('cq_6a32559edd124f4c', 'diag_working_capital', 0.85),
    ('cq_8f3451bfef79461a', 'diag_working_capital', 0.80),
    ('cq_937fb515976c478e', 'diag_working_capital', 0.85),
    ('cq_9ab5e8c8c4324869', 'diag_working_capital', 0.80),
    ('cq_9e0bf1f31c534a9d', 'diag_working_capital', 0.70),
    ('cq_a96c6fec45804166', 'diag_working_capital', 0.75),
    ('cq_aa3fd65f62164c14', 'diag_working_capital', 0.70),
    ('cq_c4f1bb3e728642d3', 'diag_working_capital', 0.95),
    ('cq_cf0c497b90d54299', 'diag_working_capital', 0.70),
    ('cq_ecde485624a840eb', 'diag_working_capital', 0.70),
    ('cq_f2bcb5e7eb4e4110', 'diag_working_capital', 0.70)
) AS v(question_id, diagram_id, relevance)
JOIN canonical.canonical_questions q ON q.id = v.question_id
JOIN canonical.diagrams d ON d.id = v.diagram_id
ON CONFLICT (question_id, diagram_id) DO UPDATE SET
    relevance = EXCLUDED.relevance;
