-- 060_curriculum_lessons.sql
-- P2.10 curriculum fill (plan 2026-09-23-001).
-- 8 modules covering accounting, EV, comps, DCF, LBO, M&A, PE fund mechanics
-- and behavioural. Real lesson body_markdown for every lesson and concept lab, at least three
-- export question ids per checkpoint (replaces the 039 seeds, fixing the duplicated LBO id),
-- and diagram checkpoints pointed at the 059 diagrams.
-- Generated by scripts/curriculum/build-migrations.ts from apps/web/lib/data/curriculum. Do not edit by hand.

INSERT INTO canonical.concepts (id, slug, title, summary, track, metadata_json, publishable)
VALUES
    ('concept_accounting_foundations', 'accounting-foundations', 'Accounting Foundations', 'Three statements, accruals, working capital, and common interview adjustments.', 'IB', '{"domain":"ib","prerequisites":[],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_ev_equity_value', 'ev-equity-value', 'Enterprise Value and Equity Value', 'Bridge market value, net debt, minority interest, associates, and diluted shares.', 'IB', '{"domain":"ib","prerequisites":["concept_accounting_foundations"],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_valuation_comps', 'valuation-comps', 'Comps and Precedent Transactions', 'Relative valuation: peer selection, multiples, control premiums, and the football field.', 'IB', '{"domain":"ib","prerequisites":["concept_ev_equity_value"],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_dcf_wacc', 'dcf-wacc', 'DCF and WACC', 'Forecast free cash flow, terminal value, discount rates, sensitivities, and the DDM for banks.', 'IB', '{"domain":"both","prerequisites":["concept_accounting_foundations","concept_ev_equity_value"],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_lbo_paper_lbo', 'lbo-paper-lbo', 'LBO and Paper LBO', 'Sources and uses, debt schedule, cash sweep, exit multiple, and returns math.', 'PE', '{"domain":"pe","prerequisites":["concept_dcf_wacc"],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_merger_model', 'merger-model', 'M&A and Merger Models', 'Purchase price, funding mix, goodwill, synergies, and accretion / dilution.', 'IB', '{"domain":"ib","prerequisites":["concept_accounting_foundations","concept_ev_equity_value"],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_pe_fund_mechanics', 'pe-fund-mechanics', 'PE Fund Mechanics', 'LPs and GPs, fees and carry, the distribution waterfall, returns metrics, and diligence.', 'PE', '{"domain":"pe","prerequisites":["concept_lbo_paper_lbo"],"seed":"060_curriculum_lessons"}'::jsonb, true),
    ('concept_behavioural_story', 'behavioural-story', 'Behavioural Story', 'Personal story, motivation, STAR stories, and fit answers.', 'IB', '{"domain":"both","prerequisites":[],"seed":"060_curriculum_lessons"}'::jsonb, true)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    track = EXCLUDED.track,
    metadata_json = concepts.metadata_json || EXCLUDED.metadata_json,
    publishable = EXCLUDED.publishable,
    updated_at = now();

INSERT INTO canonical.learning_modules (
    id, slug, title, summary, track, domain, estimated_minutes, metadata_json, publishable
)
VALUES
    ('module_accounting_foundations', 'accounting-foundations', 'Accounting Foundations', 'Build the three-statement base required for technical interview answers.', 'IB', 'ib', 50, '{"seed":"060_curriculum_lessons","level":"foundation","order":1}'::jsonb, true),
    ('module_ev_equity_value', 'ev-equity-value', 'EV and Equity Value', 'Learn the bridge between enterprise value, equity value, claims, and diluted shares.', 'IB', 'ib', 45, '{"seed":"060_curriculum_lessons","level":"foundation","order":2}'::jsonb, true),
    ('module_valuation_comps', 'valuation-comps', 'Valuation: Comps and Precedents', 'Value a business against peers and past deals, and present the result on a football field.', 'IB', 'ib', 45, '{"seed":"060_curriculum_lessons","level":"core","order":3}'::jsonb, true),
    ('module_dcf_wacc', 'dcf-wacc', 'DCF and WACC', 'Turn forecasts into value with WACC, terminal value, sensitivities, and the DDM.', 'IB', 'both', 60, '{"seed":"060_curriculum_lessons","level":"core","order":4}'::jsonb, true),
    ('module_lbo_paper_lbo', 'lbo-paper-lbo', 'LBO and Paper LBO', 'Practice sponsor returns math, debt schedules, and paper LBO shortcuts.', 'PE', 'pe', 70, '{"seed":"060_curriculum_lessons","level":"core","order":5}'::jsonb, true),
    ('module_merger_model', 'merger-model', 'M&A and Merger Models', 'Walk through a merger model, goodwill, funding choices, and accretion / dilution.', 'IB', 'ib', 50, '{"seed":"060_curriculum_lessons","level":"core","order":6}'::jsonb, true),
    ('module_pe_fund_mechanics', 'pe-fund-mechanics', 'PE Fund Mechanics', 'How funds raise, invest and distribute capital, and how deals are underwritten.', 'PE', 'pe', 45, '{"seed":"060_curriculum_lessons","level":"advanced","order":7}'::jsonb, true),
    ('module_behavioural_story', 'behavioural-story', 'Behavioural Story', 'Shape fit, motivation, and STAR stories for banking and PE interviews.', 'IB', 'both', 40, '{"seed":"060_curriculum_lessons","level":"foundation","order":8}'::jsonb, true)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    track = EXCLUDED.track,
    domain = EXCLUDED.domain,
    estimated_minutes = EXCLUDED.estimated_minutes,
    metadata_json = learning_modules.metadata_json || EXCLUDED.metadata_json,
    publishable = EXCLUDED.publishable,
    updated_at = now();

DELETE FROM canonical.learning_module_prerequisites p
WHERE p.module_id IN ('module_accounting_foundations', 'module_ev_equity_value', 'module_valuation_comps', 'module_dcf_wacc', 'module_lbo_paper_lbo', 'module_merger_model', 'module_pe_fund_mechanics', 'module_behavioural_story')
  AND NOT EXISTS (
    SELECT 1
    FROM (VALUES
    ('module_ev_equity_value', 'module_accounting_foundations'),
    ('module_valuation_comps', 'module_ev_equity_value'),
    ('module_dcf_wacc', 'module_accounting_foundations'),
    ('module_dcf_wacc', 'module_ev_equity_value'),
    ('module_lbo_paper_lbo', 'module_accounting_foundations'),
    ('module_lbo_paper_lbo', 'module_ev_equity_value'),
    ('module_lbo_paper_lbo', 'module_dcf_wacc'),
    ('module_merger_model', 'module_accounting_foundations'),
    ('module_merger_model', 'module_ev_equity_value'),
    ('module_pe_fund_mechanics', 'module_lbo_paper_lbo')
    ) AS keep(module_id, prerequisite_module_id)
    WHERE keep.module_id = p.module_id
      AND keep.prerequisite_module_id = p.prerequisite_module_id
  );

INSERT INTO canonical.learning_module_prerequisites (module_id, prerequisite_module_id)
VALUES
    ('module_ev_equity_value', 'module_accounting_foundations'),
    ('module_valuation_comps', 'module_ev_equity_value'),
    ('module_dcf_wacc', 'module_accounting_foundations'),
    ('module_dcf_wacc', 'module_ev_equity_value'),
    ('module_lbo_paper_lbo', 'module_accounting_foundations'),
    ('module_lbo_paper_lbo', 'module_ev_equity_value'),
    ('module_lbo_paper_lbo', 'module_dcf_wacc'),
    ('module_merger_model', 'module_accounting_foundations'),
    ('module_merger_model', 'module_ev_equity_value'),
    ('module_pe_fund_mechanics', 'module_lbo_paper_lbo')
ON CONFLICT (module_id, prerequisite_module_id) DO NOTHING;

INSERT INTO canonical.learning_module_concepts (module_id, concept_id)
VALUES
    ('module_accounting_foundations', 'concept_accounting_foundations'),
    ('module_ev_equity_value', 'concept_ev_equity_value'),
    ('module_valuation_comps', 'concept_valuation_comps'),
    ('module_dcf_wacc', 'concept_dcf_wacc'),
    ('module_lbo_paper_lbo', 'concept_lbo_paper_lbo'),
    ('module_merger_model', 'concept_merger_model'),
    ('module_pe_fund_mechanics', 'concept_pe_fund_mechanics'),
    ('module_behavioural_story', 'concept_behavioural_story')
ON CONFLICT (module_id, concept_id) DO NOTHING;

INSERT INTO canonical.learning_module_checkpoints (
    id, module_id, kind, title, position, concept_id, diagram_id, question_ids, body_markdown, metadata_json
)
VALUES
    (
        'chk_accounting_lesson',
        'module_accounting_foundations',
        'lesson',
        'Three statements and accrual logic',
        1,
        'concept_accounting_foundations',
        NULL,
        '["cq_63504fd1349e41a3","cq_f12a05458b2a4e0b","cq_68b428ba6b9d444f","cq_7eb46b60e55140cb"]'::jsonb,
        $$## Why interviewers start here

Almost every technical interview opens with "walk me through the three statements". The interviewer is not testing memory of line items — they want to hear that you understand **how the statements link**, because every model you will build (DCF, LBO, merger) is a three-statement model underneath.

## The three statements in one breath

- **Income statement** — revenue and expenses over a period, on an **accrual** basis, ending at net income.
- **Balance sheet** — assets = liabilities + shareholders' equity at a point in time.
- **Cash flow statement** — starts at net income, adjusts for non-cash items and changes in working capital, then adds investing and financing cash flows to reach the net change in cash.

A strong 30-second answer: "The income statement shows profitability. Net income flows to the top of the cash flow statement, which adds back non-cash charges like D&A, adjusts for working capital, and adds investing and financing activity to get the change in cash. That change updates cash on the balance sheet, and net income less dividends flows into retained earnings, so the balance sheet balances."

## Accrual versus cash

Accrual accounting records revenue when it is **earned** and expenses when they are **incurred**, not when cash moves. That is why the cash flow statement exists: it reconciles accrual profit to actual cash. Credit sales raise revenue and accounts receivable without any cash; D&A spreads a past capex payment over the asset's life.

## Worked example: depreciation up by $10 (25% tax)

| Statement | Change |
| --- | --- |
| Income statement | Pre-tax income −10, taxes −2.5, net income −7.5 |
| Cash flow statement | Net income −7.5, add back D&A +10, cash +2.5 |
| Balance sheet | Cash +2.5, PP&E −10, so assets −7.5; retained earnings −7.5 |

Assets fall by 7.5 and equity falls by 7.5, so the balance sheet balances. The **+2.5 of cash is the tax shield**: depreciation is non-cash, but it lowers the tax bill.

## Worked example: inventory up by $10, paid in cash

- Income statement: **no change** — inventory is expensed through COGS only when it is sold.
- Cash flow statement: the increase in inventory is a use of cash, so cash from operations falls by 10.
- Balance sheet: cash −10, inventory +10. Total assets are unchanged.

## Common traps

1. Forgetting taxes when an expense changes (the answer is never "net income −10" for a pre-tax item).
2. Saying depreciation "creates cash". It reduces taxes; the add-back only reverses a non-cash expense.
3. Putting dividends on the income statement — they reduce retained earnings and appear in financing cash flow.
4. Mixing up the direction of working capital: an **increase** in an operating asset uses cash.

## How to practise

Say the linkage out loud, then run two or three single-line changes (D&A, inventory, accrued compensation, a debt-funded asset purchase) through all three statements and finish every answer with "and the balance sheet balances because…". Open the diagram checkpoints next to see the full set of linkages.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_accounting_linkages_diagram',
        'module_accounting_foundations',
        'diagram',
        'Full three-statement linkages',
        2,
        'concept_accounting_foundations',
        'diag_three_statement_linkages',
        '["cq_6f524f3351104f10","cq_fbc5552112444919","cq_15099edc274d49b1","cq_1f3979ed0fb24cf4"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_accounting_wc_lab',
        'module_accounting_foundations',
        'concept_lab',
        'Working capital: where cash hides',
        4,
        'concept_accounting_foundations',
        'diag_working_capital',
        '["cq_c4f1bb3e728642d3","cq_3a4a719580654e34","cq_937fb515976c478e","cq_aa3fd65f62164c14","cq_006f605c21ee4e84"]'::jsonb,
        $$## What working capital measures

Working capital is **current assets minus current liabilities**. In valuation and modelling we usually care about **operating** working capital, which excludes cash and debt:

> Operating NWC = accounts receivable + inventory + prepaid expenses − accounts payable − accrued expenses − deferred revenue

It measures how much cash is tied up in running the business day to day.

## The cash conversion cycle

Cash buys inventory, inventory is sold on credit, receivables are collected, and suppliers are paid on their own terms. Three day-count ratios describe the loop:

| Metric | Formula | Meaning |
| --- | --- | --- |
| DSO | AR ÷ revenue × 365 | days to collect from customers |
| DIO | inventory ÷ COGS × 365 | days inventory sits before sale |
| DPO | AP ÷ COGS × 365 | days taken to pay suppliers |

**Cash conversion cycle = DIO + DSO − DPO.**

### Worked example

Revenue 730, COGS 438, accounts receivable 80, inventory 60, accounts payable 36.

- DSO = 80 ÷ 730 × 365 = **40 days**
- DIO = 60 ÷ 438 × 365 = **50 days**
- DPO = 36 ÷ 438 × 365 = **30 days**
- Cash conversion cycle = 50 + 40 − 30 = **60 days**

If the company negotiated 45-day supplier terms, payables would rise to 54 (438 × 45 ÷ 365) and the cycle would shrink to 45 days, releasing 18 of cash.

## How changes hit the cash flow statement

The rule to memorise: **an increase in an operating asset uses cash; an increase in an operating liability frees cash.**

- Accounts receivable up 20 → cash from operations −20 (revenue was booked but not collected).
- Accrued compensation up 10 → the expense hits net income (−7.5 after 25% tax), but the accrual is added back (+10), so cash rises 2.5.
- Deferred revenue up 15 → cash collected before revenue is earned, so cash from operations +15.

## Is negative working capital bad?

Not necessarily. Retailers, restaurants and subscription software companies often have **negative working capital** because customers pay up front (cash or deferred revenue) while suppliers are paid later. That is a sign of bargaining power and funds growth. It is a warning sign only when it comes from stretching payables because the company cannot pay its bills.

## Interview angles

1. "Why does an increase in accounts receivable reduce cash flow?" Revenue was recognised on an accrual basis but the customer has not paid yet.
2. "What is the difference between accounts receivable and deferred revenue?" AR is revenue earned but not collected (an asset); deferred revenue is cash collected but not yet earned (a liability).
3. In a DCF, the **change** in NWC, not the level, enters unlevered free cash flow. Growing companies usually invest in working capital every year.

Use the working capital cycle diagram in this module to trace each arrow before you answer.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_accounting_drill',
        'module_accounting_foundations',
        'drill',
        'Working capital and depreciation drill',
        5,
        'concept_accounting_foundations',
        NULL,
        '["cq_4d057d34ba8e402e","cq_516b5dc422ef4aa9","cq_825afa2d5cb04352","cq_ff3ee3f76d944b6b","cq_1b2ce929a7d140fe","cq_2e8a4ce2324d4638"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_ev_lesson',
        'module_ev_equity_value',
        'lesson',
        'EV versus equity value',
        1,
        'concept_ev_equity_value',
        NULL,
        '["cq_d3cb5b15d30a4d36","cq_ccb203dbbac0404c","cq_a38f594a71df47da","cq_6b8932f1b2684545"]'::jsonb,
        $$## Two values, two audiences

**Equity value** is what the company is worth to **common shareholders** only: diluted shares outstanding × share price for a public company. **Enterprise value** is the value of the **core operating business** to **all capital providers** — equity, debt, preferred stock and minority holders.

We look at both because they answer different questions. Equity value tells you what a share is worth; enterprise value lets you compare businesses regardless of how they are financed and is what an acquirer effectively pays for the operations.

## The bridge

> Enterprise value = equity value + debt + preferred stock + non-controlling interest − cash − non-operating assets (for example equity investments)

- **Add debt and preferred stock** — they are claims on the operating business from other investors.
- **Add non-controlling interest** — the parent consolidates 100% of a majority-owned subsidiary's EBITDA, so EV must include the minority owners' slice to stay consistent with the metric.
- **Subtract cash** — cash is not needed to run the core business, and an acquirer effectively gets it back.
- **Subtract equity investments / associates** — their income is not in consolidated EBITDA.

### Worked example

Share price 20, 50 million diluted shares → equity value **1,000**. Debt 400, preferred 50, NCI 30, cash 150, equity investments 30.

EV = 1,000 + 400 + 50 + 30 − 150 − 30 = **1,300**.

Going the other way, a DCF that produces an EV of 1,300 implies equity value of 1,000, or 20 per share.

## Capital structure and EV

If the company borrows 100 and holds it as cash, equity value does not change, debt rises by 100 and cash rises by 100, so **EV is unchanged**. EV changes when the operating business changes; equity value changes with both operations and financing. That is the logic interviewers are testing.

## Matching multiples to the right value

| Multiple | Numerator | Why |
| --- | --- | --- |
| EV / EBITDA, EV / revenue, EV / EBIT | EV | metric is before interest, available to all capital providers |
| P / E, equity value / levered FCF | equity value | metric is after interest, available to equity only |

Mixing them (equity value / EBITDA) is a classic red flag.

## Edge cases interviewers like

1. **Negative EV** — possible when cash exceeds market capitalisation plus debt, often a distressed or cash-rich company the market doubts.
2. **Negative equity value** — not possible for market value (share price cannot go below zero), but **shareholders' equity** (book value) can be negative after large losses or dividend recaps.
3. **Equity value vs shareholders' equity** — market value versus accounting book value.
4. **Market vs book** — use market values where they exist (share price, trading debt prices if very different from par).

Next, open the EV bridge diagram and then test yourself in the fill-in quiz.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_ev_diagram',
        'module_ev_equity_value',
        'diagram',
        'EV to equity bridge',
        2,
        'concept_ev_equity_value',
        'diag_ev_bridge',
        '["cq_8a75fe6712ca4fe3","cq_16283e97421d4821","cq_32daa6c06e3a46ad","cq_6b41bb93a2c24040"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_ev_dilution_lab',
        'module_ev_equity_value',
        'concept_lab',
        'Diluted shares: treasury stock method and converts',
        4,
        'concept_ev_equity_value',
        NULL,
        '["cq_40b72295f4ed403c","cq_1c3adf726d644ee0","cq_b0e29150b0fd4631","cq_e05fef96bfae4425","cq_2a195733afe14235"]'::jsonb,
        $$## Why diluted shares matter

Equity value per share is only as good as the share count. Options, warrants, restricted stock units and convertible securities can all turn into common shares, so interview answers and models use **fully diluted shares outstanding**, not basic shares.

## Treasury stock method (options and warrants)

1. Include only **in-the-money** instruments (strike price below the current share price).
2. Assume they are exercised and the company receives strike × number of options in cash.
3. Assume the company uses that cash to **buy back shares** at the current price.
4. Net new shares = options − buyback shares.

### Worked example

100 shares outstanding at 10.00. 10 options with a strike price of 5.00.

- Exercise proceeds = 10 × 5.00 = 50
- Shares repurchased = 50 ÷ 10.00 = 5
- Net new shares = 10 − 5 = **5**
- Diluted shares = **105**, diluted equity value = 105 × 10.00 = **1,050**

If the strike were 12.00 the options would be out of the money and ignored. RSUs have no strike price, so they are simply added in full.

## Convertible bonds (if-converted method)

Compare the share price with the **conversion price** (par value ÷ conversion ratio). If the share price is higher, the bond is in the money: count the new shares and remove the bond from debt in the EV bridge. If not, keep it as debt.

### Worked example

1 million shares at 100.00. 10 million of convertible bonds with 1,000 par and a conversion price of 50.00.

- Each bond converts into 1,000 ÷ 50 = 20 shares; there are 10,000 bonds
- New shares = 10,000 × 20 = **200,000**
- Share price 100 > conversion price 50, so convert: diluted shares = **1.2 million**
- Diluted equity value = 1.2 million × 100 = **120 million**, and the 10 million of converts is **not** also counted as debt

Counting the convert as both debt and equity is the most common mistake here.

## Other dilutive items

- **Preferred stock** that converts into common is treated like a convertible.
- **Earnouts and contingent shares** — include if the conditions are likely to be met.
- When a deal price rather than the market price is used (M&A), recompute dilution at the **offer price**, because more options are in the money.

## How much dilution is too high?

There is no fixed rule, but if diluted equity value is more than roughly 10–20% above basic equity value, investors and boards focus on it, and management incentive plans come under scrutiny.

## Interview checklist

- State the method (treasury stock or if-converted).
- Show the arithmetic in one line.
- Say where the item goes in the EV bridge.
- Mention that you recompute at the offer price in an acquisition.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_ev_drill',
        'module_ev_equity_value',
        'drill',
        'EV edge cases drill',
        5,
        'concept_ev_equity_value',
        NULL,
        '["cq_617fc6eaff9a441a","cq_7f3b290cb078425d","cq_5c123fab555c4855","cq_858f9b80b4334667","cq_5a955926b69a4ff5"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_comps_lesson',
        'module_valuation_comps',
        'lesson',
        'Trading comps and precedent transactions',
        1,
        'concept_valuation_comps',
        NULL,
        '["cq_feb4ddab223041e3","cq_0220996bda424750","cq_5c2e5cbb236642d2","cq_637cea43aead407a"]'::jsonb,
        $$## Relative valuation in one sentence

Comparable companies ("trading comps") and precedent transactions value a business by asking **what similar assets are worth today**, expressed as multiples of a financial metric.

## Trading comps step by step

1. **Screen** for peers on industry, business model, size, growth, margins and geography.
2. **Spread** the comps: equity value, EV, and LTM and forward revenue, EBITDA, EBIT and EPS. Calendarise fiscal years and use consensus estimates for forward numbers.
3. **Compute multiples** — EV / revenue, EV / EBITDA, EV / EBIT, P / E.
4. **Pick a range**, usually around the median (25th–75th percentile), and justify premiums or discounts.
5. **Apply** the range to the target's metric and bridge from EV to equity value per share.

### Worked example

Peer EV / EBITDA multiples: 7.5x, 8.0x, 9.0x, 10.0x, 11.5x. Median 9.0x, interquartile range about 8.0x–10.0x.

Target EBITDA 50 → implied EV **400–500**. Net debt 100 → equity value **300–400**. 20 million diluted shares → **15.00–20.00 per share**.

## Precedent transactions

Same mechanics, but the multiples are what acquirers **paid** for similar companies, usually EV / LTM EBITDA at announcement. Precedents typically come out **higher** than trading comps because they include a **control premium** (often 20–40%) and expected synergies.

Weaknesses to mention:

- Data is stale — market conditions and interest rates change.
- Few truly comparable deals, and deal terms (earnouts, stock vs cash) muddy the multiple.
- Disclosure is thin for private targets.

## Choosing the right multiple

| Situation | Useful multiple |
| --- | --- |
| Mature, profitable | EV / EBITDA, P / E |
| Capital intensive (D&A differs across peers) | EV / EBIT or EV / (EBITDA − capex) |
| Unprofitable, high growth | EV / revenue, EV / gross profit |
| Banks and insurers | P / E, P / tangible book |
| Industry specific | EV / subscribers, EV / reserves, price / FFO for REITs |

Always pair EV with pre-interest metrics and equity value with post-interest metrics.

## Why would a company trade at a premium to peers?

Faster growth, higher margins or returns on capital, more recurring revenue, a stronger competitive position, or scarcity value. If growth and profitability are similar, look for differences in risk (customer concentration, leverage), liquidity and market sentiment.

## Interview answer template

"I'd pick 5–10 peers on industry, size and growth, compute EV / EBITDA and P / E on LTM and forward numbers, and take a range around the median. For precedents I'd use deals from the last few years in the sector; those multiples are usually higher because of the control premium. I'd apply both ranges to the target's EBITDA, subtract net debt, and divide by diluted shares."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_comps_diagram',
        'module_valuation_comps',
        'diagram',
        'From peer multiples to implied value',
        2,
        'concept_valuation_comps',
        'diag_comps_precedents',
        '["cq_442696f0eac84c46","cq_4cb8d04837d64e81","cq_465b1f33d4914874","cq_2827195a0ae241f1"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_comps_football_lab',
        'module_valuation_comps',
        'concept_lab',
        'Presenting value: the football field',
        3,
        'concept_valuation_comps',
        'diag_football_field',
        '["cq_f9a00579c6f24f44","cq_a06ed529e9784dbd","cq_82cfeca372c34d0a","cq_29fb1b768111452f"]'::jsonb,
        $$## What a football field is for

A football field is a horizontal bar chart that shows the **implied value range from each methodology side by side** — usually per share, sometimes as enterprise value. Bankers use it in fairness opinions, pitch books and board presentations to show where a valuation or an offer price sits.

## Typical rows

| Methodology | What drives the range | Where it usually sits |
| --- | --- | --- |
| 52-week trading range | market prices | anchor for public companies |
| Analyst price targets | broker research | similar to trading |
| Trading comps | peer multiple range × metric | minority, no premium |
| Precedent transactions | deal multiple range × metric | often highest (control premium) |
| DCF | WACC and terminal value sensitivities | widest range |
| LBO | purchase price for a 20–25% IRR | often the floor |

### Worked example

Implied share price ranges: 52-week range 38–52, trading comps 40–55, precedents 48–63, DCF 45–70, LBO at a 20–25% IRR 36–50. The current price is 42.

Most methods overlap between roughly **48 and 55**, so an offer in that zone is defensible: it is a premium of about 14–31% to the current price and inside the precedent range. An offer of 45 would look light because it sits below the precedent range.

## Why the LBO is often the floor

A financial sponsor can pay only what still earns its target return using leverage and no strategic synergies. A strategic buyer with synergies can usually outbid that price, so the LBO range marks a level a seller should not go below.

## Ranking the methodologies

A common interview question is "rank the methods from highest to lowest". A good answer avoids a rigid rule: **precedents are usually highest** because of the control premium; the **DCF is the most variable** because it depends on assumptions; **trading comps** are typically below precedents. Market conditions can flip this — in a sell-off, precedents from a hotter market look expensive and trading comps look cheap.

## How to build a sensible range

- Use the **interquartile range** of multiples, not the minimum and maximum.
- For the DCF, sensitise WACC (±0.5–1%) and terminal growth (±0.5%) or the exit multiple (±1.0x).
- Keep the same metric definition (LTM vs forward, adjusted vs reported) across rows.
- Show the offer price and current price as vertical lines so the reader can see premiums instantly.

## Interview framing

"I wouldn't average the methods. I'd look at where the ranges overlap and weight the most reliable ones for this company — for a stable, cash-generative business I'd lean on the DCF and precedents; for a volatile one, trading comps and the LBO floor."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_comps_drill',
        'module_valuation_comps',
        'drill',
        'Multiples and relative valuation drill',
        4,
        'concept_valuation_comps',
        NULL,
        '["cq_f06907cf13db44ab","cq_50b4f448a2c9438b","cq_98ee7947a97c4c85","cq_281a64f347a44380","cq_0ed8c9f7a4ae4d14","cq_ed6cc02b51584998"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_dcf_lesson',
        'module_dcf_wacc',
        'lesson',
        'Forecasts, WACC, and terminal value',
        1,
        'concept_dcf_wacc',
        NULL,
        '["cq_1990bf98f34d4d15","cq_b1b65546c5624d38","cq_71a764c3f71741ff","cq_14f0acda1fd344cb","cq_0051b6ee2aee4244"]'::jsonb,
        $$## The idea

A discounted cash flow values a business as the **present value of the cash it will generate for all capital providers**. It is an intrinsic method: it depends on your forecast and discount rate, not on what peers trade at.

## Five steps

1. **Forecast unlevered free cash flow** for 5–10 years — long enough for the business to reach a steady state.
2. **Calculate WACC**, the blended return required by equity and debt investors.
3. **Estimate terminal value** for all years after the forecast.
4. **Discount** the forecast cash flows and terminal value to today and sum them to enterprise value.
5. **Bridge to equity value** and divide by diluted shares.

## Unlevered free cash flow

> UFCF = EBIT × (1 − tax rate) + D&A − capex − increase in net working capital

It is "unlevered" because it is before interest, so it belongs to both debt and equity holders — which is why it is discounted at WACC. **Levered** free cash flow (after interest and debt repayments) belongs to equity only, is discounted at the **cost of equity**, and produces equity value directly.

## WACC

> WACC = E/V × cost of equity + D/V × pre-tax cost of debt × (1 − t)

Cost of equity usually comes from CAPM: risk-free rate + levered beta × equity risk premium. Beta is taken from peers, **unlevered** to strip out their capital structures, then **relevered** at the target's structure. More debt raises the cost of equity (more financial risk) but can lower WACC at first because debt is cheaper and tax-deductible.

## Terminal value, with numbers

**Gordon growth:** TV = UFCF in year n × (1 + g) ÷ (WACC − g).

Year-5 UFCF 100, WACC 10%, g 2%: TV = 102 ÷ 0.08 = **1,275**. Discount factor for year 5 is 1 ÷ 1.10^5 = 0.621, so the PV of TV is about **792**.

**Exit multiple:** TV = year-n EBITDA × multiple. With year-5 EBITDA of 150 at 8.0x, TV = **1,200**. Cross-check the implied perpetual growth rate: g = (TV × WACC − UFCF) ÷ (TV + UFCF) = (120 − 100) ÷ 1,300 ≈ **1.5%**, which is sensible. If the implied growth were 6%, the multiple would be too high.

Terminal value is often 60–80% of total EV, which is why sensitivity tables matter.

## Sensitivities and judgement

- A 1% change in the discount rate usually moves value more than a 1% change in revenue, because it compounds through every year and the terminal value.
- Show WACC vs terminal growth (or exit multiple) tables, and revenue growth vs margin tables.
- The **mid-year convention** assumes cash arrives mid-year, discounting year 1 by 0.5 periods instead of 1, which raises value slightly.

## When not to use a DCF

When cash flows are unpredictable (early-stage companies), negative for a long time, or when debt is operating raw material, as with **banks and insurers** — use a dividend discount model or P / TBV there instead.

## Interview answer template

"Project unlevered free cash flow for five to ten years, discount it at WACC, add the present value of a terminal value from either Gordon growth or an exit multiple, and that is enterprise value. Subtract net debt and other claims to get equity value and divide by diluted shares."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_dcf_diagram',
        'module_dcf_wacc',
        'diagram',
        'DCF flow diagram',
        2,
        'concept_dcf_wacc',
        'diag_dcf_wacc',
        '["cq_704b3332dc224084","cq_a8bae917c43242a3","cq_3b84b0d0b2674433","cq_e3896996740d4569"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_dcf_wacc_diagram',
        'module_dcf_wacc',
        'diagram',
        'WACC build-up diagram',
        3,
        'concept_dcf_wacc',
        'diag_wacc_build',
        '["cq_144739edafb9417d","cq_e9a215d4c2ff489f","cq_667eaff09bdb443f","cq_67f4db3705834718"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_dcf_ddm_lab',
        'module_dcf_wacc',
        'concept_lab',
        'When a DCF does not fit: the DDM for banks',
        5,
        'concept_dcf_wacc',
        'diag_ddm',
        '["cq_00a1635dbfc14545","cq_21ab1c196db34188","cq_9f0737b1e2d0463e"]'::jsonb,
        $$## Why banks break the normal DCF

For an industrial company, debt is financing and interest sits below operating profit. For a **bank**, deposits and borrowings are the raw material: interest expense is a cost of goods sold. There is no meaningful EBITDA, capex or working capital, and regulators require the bank to hold a minimum level of equity capital. So we **value the equity directly** using a dividend discount model (DDM), discounting at the **cost of equity**, not WACC.

## Steps in a DDM

1. **Project the balance sheet** — loans and deposits drive interest income and expense.
2. **Project net income** — net interest income + fees − operating costs − loan loss provisions − taxes.
3. **Set the capital requirement** — e.g. keep CET1 capital at 11% of risk-weighted assets. Growing the balance sheet requires retaining earnings.
4. **Dividends = net income − capital required to support growth.** Excess capital above the target can be treated as distributable.
5. **Discount dividends and a terminal value at the cost of equity.** Terminal value comes from Gordon growth on dividends or a P / E or price to tangible book multiple.
6. The sum is **equity value**; divide by diluted shares. There is **no EV bridge**.

## Worked example: Gordon growth DDM

Next year's net income 120, return on equity (ROE) 12%, so beginning book equity is 1,000. The bank retains one third of earnings to fund growth, so sustainable growth g = ROE × retention = 12% × 1/3 = **4%**. Dividends next year = 120 × 2/3 = **80**. Cost of equity 10%.

- Equity value = 80 ÷ (10% − 4%) = **1,333**
- Implied price / book = 1,333 ÷ 1,000 = **1.33x**

This matches the justified P / B formula: (ROE − g) ÷ (Ke − g) = (12% − 4%) ÷ (10% − 4%) = 1.33x. The intuition interviewers want: **a bank trades above book only if its ROE exceeds its cost of equity.** At ROE of 10% the same bank would be worth exactly book value.

## What else differs for financial institutions

- **Multiples:** P / E, P / book and P / tangible book instead of EV / EBITDA.
- **Key metrics:** net interest margin, efficiency ratio, CET1 ratio, non-performing loans, ROE and ROTE.
- **Insurers:** DDM or embedded value; float and reserves play the role of deposits.

## Interview traps

1. Discounting dividends at WACC — dividends belong to equity, so use the cost of equity.
2. Adding debt or subtracting cash to get to equity value — the DDM already produces equity value.
3. Forgetting the capital constraint: a bank cannot pay out all its earnings if it wants to grow its loan book.

## One-line answer

"For a bank I'd use a dividend discount model: project net income, retain enough to meet capital requirements, treat the rest as dividends, and discount dividends plus a terminal value at the cost of equity to get equity value directly."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_dcf_drill',
        'module_dcf_wacc',
        'drill',
        'DCF judgement drill',
        6,
        'concept_dcf_wacc',
        NULL,
        '["cq_99e2dd9d186f447e","cq_7d6d75264c3f4195","cq_cdd7855a21314692","cq_25a4f6848fa24270","cq_2b6abab9a11d43a3","cq_1a11f32723f045c5"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_lbo_lesson',
        'module_lbo_paper_lbo',
        'lesson',
        'How an LBO works',
        1,
        'concept_lbo_paper_lbo',
        NULL,
        '["cq_367c383e66594921","cq_14a8c83d53a945d8","cq_848e98a343c14dc3","cq_aff6fd944e474755"]'::jsonb,
        $$## What an LBO is

In a leveraged buyout a financial sponsor (a private equity firm) buys a company using a **large amount of debt** — often 50–70% of the purchase price — and a smaller equity cheque. The company's own cash flow services and repays the debt, and the sponsor sells after 3–7 years. The target return is typically a **20–25% IRR** and a **2.0–3.0x MOIC**.

## Walk through a basic LBO model

1. **Transaction assumptions** — purchase multiple (e.g. 10.0x EBITDA), debt tranches and leverage (e.g. 6.0x EBITDA), interest rates, fees.
2. **Sources and uses** — uses are the equity purchase price, refinanced debt and fees; sources are the debt tranches, any rollover and the sponsor equity **plug**.
3. **Adjust the balance sheet** — new debt, new equity, write-ups and goodwill; eliminate the target's old equity.
4. **Project the income statement and cash flow** — EBITDA, interest on the new debt, taxes, capex and working capital to reach free cash flow.
5. **Debt schedule** — mandatory amortization, then optional repayment with excess cash; the revolver covers shortfalls.
6. **Exit** — EBITDA in the exit year × exit multiple = exit EV; subtract net debt for exit equity.
7. **Returns** — MOIC and IRR on the sponsor's equity, with sensitivities to entry and exit multiples and leverage.

## Why leverage boosts returns

- **Less equity** is needed for the same purchase price, so any value gain is spread over a smaller base.
- **Debt paydown** from operating cash flow accrues to the equity holders.
- **Interest is tax-deductible**, creating a tax shield.

Leverage cuts both ways: if the business underperforms, fixed interest and covenants can wipe out the equity.

## Can more leverage lower IRR?

Yes. Beyond a point, extra debt costs more (higher coupons, PIK, tighter covenants), interest absorbs the free cash flow that would otherwise repay debt, and the risk of breaching covenants or needing an equity cure rises. If the after-tax cost of the marginal debt exceeds the return the business earns on its capital, more leverage dilutes returns.

## What makes a good LBO candidate

- Stable, predictable cash flow to support debt.
- Low capex and working capital needs.
- Strong market position and pricing power.
- Opportunities to improve margins or grow (organically or via add-ons).
- A realistic exit route — strategic sale, secondary buyout or IPO.
- Assets that can serve as collateral, and a capable management team.

## Variables that matter most

Purchase and exit multiples and EBITDA growth usually move returns the most; leverage and interest rates come next. Always ask how the deal performs if the exit multiple is 1–2 turns lower than entry.

## Interview answer template

"A sponsor buys a company with mostly debt, uses the company's cash flow to pay interest and reduce debt over five years or so, then sells it. In the model we set assumptions, build sources and uses, project cash flow and a debt schedule, calculate exit equity, and measure IRR and MOIC."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_lbo_concept_lab',
        'module_lbo_paper_lbo',
        'concept_lab',
        'Paper LBO returns lab',
        2,
        'concept_lbo_paper_lbo',
        'diag_lbo_sources_uses',
        '["cq_38a231fb832e4a61","cq_5a0d575fc0c4498c","cq_a61d97d82d294d52","cq_1e567a8fcaa645a7"]'::jsonb,
        $$## The paper LBO format

A paper LBO is a mental-maths LBO you do with a pen in five to ten minutes. The interviewer wants a structured process and sensible rounding, not decimals.

## Step by step with numbers

**Assumptions:** EBITDA 100, purchase at 10.0x, leverage 6.0x, 5-year hold, exit at 10.0x, ignore fees and minimum cash.

1. **Entry:** EV = 100 × 10.0x = **1,000**. Debt = 6.0 × 100 = **600**. Sponsor equity = 1,000 − 600 = **400**.
2. **Operations:** EBITDA grows to **150** by year 5. Free cash flow after interest and taxes totals **300** over the hold and is used to repay debt, so debt falls to **300**.
3. **Exit:** EV = 150 × 10.0x = **1,500**. Exit equity = 1,500 − 300 = **1,200**.
4. **Returns:** MOIC = 1,200 ÷ 400 = **3.0x**. IRR ≈ **25%** (3.0x over five years is about 24.6%).

## IRR shortcuts to memorise

| MOIC | 3 years | 5 years |
| --- | --- | --- |
| 1.5x | ≈ 14% | ≈ 8% |
| 2.0x | ≈ 26% | ≈ 15% |
| 2.5x | ≈ 36% | ≈ 20% |
| 3.0x | ≈ 44% | ≈ 25% |

Doubling in five years is roughly 15%; tripling is roughly 25%.

## Attribute the gain

The equity grew by 800 (from 400 to 1,200). Split it:

- **EBITDA growth:** 50 of new EBITDA × 10.0x entry multiple = **500**
- **Multiple expansion:** exit multiple equals entry, so **0**
- **Deleveraging:** debt repaid 600 − 300 = **300**

500 + 0 + 300 = 800. Interviewers love this split because it shows where value came from.

## Sensitivity: exit one turn lower

At a 9.0x exit, EV = 1,350 and exit equity = 1,050. MOIC = 2.6x and IRR falls to about **21%**. Multiple contraction of one turn cost 150 of equity, which is why sponsors underwrite a flat or lower exit multiple.

## Back-solving the price for a target IRR

"What can we pay for a 20% IRR?" 20% for five years ≈ **2.5x**. Exit equity 1,200 ÷ 2.5 ≈ 480 of equity today. Holding debt at 600, the maximum EV is about **1,080**, or roughly **10.8x** EBITDA.

## Common mistakes

1. Forgetting to subtract remaining debt at exit.
2. Using EV instead of equity for MOIC.
3. Applying free cash flow before interest — cash available to repay debt is after interest and taxes.
4. Ignoring fees in a real deal; they add to uses and increase the equity cheque.

Use the sources and uses quiz and the returns diagrams in this module to rehearse each step.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_lbo_debt_schedule_diagram',
        'module_lbo_paper_lbo',
        'diagram',
        'Debt schedule and revolver',
        4,
        'concept_lbo_paper_lbo',
        'diag_debt_schedule',
        '["cq_0195ce6a368d4127","cq_528ffdb15fa84ae6","cq_09502737b5ef4468","cq_f5e196d8c20142f3"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_lbo_moic_diagram',
        'module_lbo_paper_lbo',
        'diagram',
        'MOIC and IRR diagram',
        5,
        'concept_lbo_paper_lbo',
        'diag_moic_irr',
        '["cq_7c29d259b4004a54","cq_e91ac5aff6c0420a","cq_d5c2dc215d83443f"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_lbo_returns_diagram',
        'module_lbo_paper_lbo',
        'diagram',
        'Paper LBO returns bridge',
        6,
        'concept_lbo_paper_lbo',
        'diag_paper_lbo_returns',
        '["cq_9f7f7b3a2b6d4761","cq_95bbf5673ab7428d","cq_c8183b1f88294c25"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_lbo_quiz',
        'module_lbo_paper_lbo',
        'quiz',
        'LBO returns quiz',
        7,
        'concept_lbo_paper_lbo',
        NULL,
        '["cq_7574e2ee51d2407f","cq_d084e736ecfb49f8","cq_9779bfc619254462","cq_0e7fbe121f71483a","cq_395837d575dc443d","cq_73b896690a3c437a"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_merger_lesson',
        'module_merger_model',
        'lesson',
        'Walk through a merger model',
        1,
        'concept_merger_model',
        NULL,
        '["cq_f6941c5fe0eb4c8c","cq_ff561da3731b44e9","cq_118a4c5d57284599","cq_6bbe0c634b1144ca"]'::jsonb,
        $$## What a merger model answers

A merger (accretion / dilution) model asks: **after buying the target, will the acquirer's earnings per share go up or down?** Public acquirers care because investors track EPS, and the model also shows ownership, credit metrics and how much synergy the deal needs.

## Walk through a merger model

1. **Project both companies' income statements** and standalone EPS.
2. **Set the purchase price** — offer price per share (current price + premium) × target diluted shares, plus any target debt refinanced and fees.
3. **Sources and uses** — fund the price with cash on hand, new debt, new acquirer stock, or a mix.
4. **Purchase price allocation** — write target assets up to fair value, create new intangibles, record a deferred tax liability on the write-ups, and plug the remainder as **goodwill**.
5. **Combine the income statements** and adjust: forgone interest on cash, new interest on debt, extra D&A on write-ups and intangibles, and synergies — all tax-effected.
6. **Pro forma EPS** = pro forma net income ÷ (acquirer shares + new shares issued). Compare with the acquirer's standalone EPS.
7. **Sensitivities** — purchase premium, cash / stock mix, synergies, interest rates.

## Goodwill with numbers

Purchase equity price 500. Target book equity 300. PP&E written up by 50; at a 25% tax rate this creates a deferred tax liability of 12.5.

> Goodwill = 500 − (300 + 50 − 12.5) = **162.5**

Goodwill is not amortised under US GAAP or IFRS; it is tested for **impairment**. An impairment signals the buyer overpaid.

## Why acquire?

- Growth that the buyer cannot achieve organically.
- **Synergies** — cost (overlapping headcount, facilities, procurement) and revenue (cross-selling, pricing).
- Market share, new products, technology or talent.
- Diversification or vertical integration.

Cost synergies are more credible and are valued more by investors; revenue synergies are harder to achieve and usually phased in.

## Cash, stock or debt?

From the acquirer's view, **cash** is usually cheapest (low interest income forgone), then **debt** (after-tax interest), then **stock** (earnings yield of the acquirer, 1 ÷ P / E, often the most expensive and dilutes ownership). Stock makes sense when the acquirer's shares are richly valued, the balance sheet cannot take more debt, or the seller wants to share in the upside.

## Why strategics can pay more than PE

Strategic buyers can count on synergies and often have a lower cost of capital and a longer horizon, so they can justify a higher price than a sponsor constrained by a target IRR.

## Interview answer template

"Project both companies, set the purchase price and how it is funded, allocate the price to assets and goodwill, combine the income statements adjusting for interest, new D&A and synergies after tax, and divide pro forma net income by the new share count. If pro forma EPS is above the acquirer's standalone EPS, the deal is accretive."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_merger_diagram',
        'module_merger_model',
        'diagram',
        'Sources and uses to pro forma EPS',
        2,
        'concept_merger_model',
        'diag_merger_model',
        '["cq_4d7ed5a72dc8404f","cq_28e19f6b22c34cd0","cq_f2133cc4655f4241","cq_196bfece926c4771"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_merger_accretion_lab',
        'module_merger_model',
        'concept_lab',
        'Accretion / dilution shortcuts',
        3,
        'concept_merger_model',
        'diag_accretion_dilution',
        '["cq_f2063ecaffef4d41","cq_d372b36ccbba4b4d","cq_027326f9e4e74d15","cq_6fdef2ea7f6243a4"]'::jsonb,
        $$## The shortcut every interviewer expects

Compare the **after-tax cost of each funding source** with the **target's earnings yield** at the purchase price.

| Funding | After-tax cost |
| --- | --- |
| Cash | interest rate earned on cash × (1 − t) |
| Debt | interest rate on new debt × (1 − t) |
| Stock | acquirer earnings yield = 1 ÷ acquirer P / E |

Target yield = 1 ÷ purchase P / E (the P / E the acquirer is paying, including the premium).

If the **weighted cost of funding is below the target yield, the deal is accretive** (before synergies and new D&A).

For an **all-stock** deal this collapses to a simple rule: accretive if the acquirer's P / E is higher than the purchase P / E of the target.

## Worked example

Acquirer: net income 100, 100 shares, EPS 1.00, share price 20.00 → P / E 20x (stock cost 5%).
Target: net income 40, purchase price 600 → purchase P / E 15x (yield 6.7%).
Funding: 50% stock, 50% new debt at 8%, tax rate 25% (debt cost 6%).

**Shortcut:** weighted cost = 0.5 × 5% + 0.5 × 6% = 5.5% < 6.7% → accretive.

**Check with numbers:**

- New shares: 300 ÷ 20.00 = 15
- After-tax interest: 300 × 8% × (1 − 25%) = 18
- Pro forma net income = 100 + 40 − 18 = 122
- Pro forma shares = 115
- Pro forma EPS = 122 ÷ 115 = **1.061**, about **6% accretive**

## Break-even synergies

If a deal is dilutive, how much pre-tax synergy is needed to break even?

> Break-even pre-tax synergies = (standalone EPS × pro forma shares − pro forma net income) ÷ (1 − t)

Suppose instead pro forma net income were 110 with 115 shares. Required net income = 1.00 × 115 = 115; shortfall 5; pre-tax synergies = 5 ÷ 0.75 ≈ **6.7**.

## Other things that make a deal dilutive

- Paying a high premium (low target yield).
- **New D&A** on written-up assets and amortisation of new intangibles.
- Transaction fees financed with debt, and higher interest rates.
- Issuing stock when the acquirer's P / E is low.

## Accretion is not value creation

An accretive deal can still destroy value if the buyer overpays relative to the target's intrinsic value, and a dilutive deal can create value if synergies arrive later. Say this unprompted — it shows judgement.

## Interview checklist

1. State the cost of each funding source after tax.
2. Compare with the target's yield at the offer price.
3. Mention synergies and new D&A as adjustments.
4. Offer to verify with a quick pro forma EPS calculation.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_merger_drill',
        'module_merger_model',
        'drill',
        'Goodwill, synergies and deal structure drill',
        4,
        'concept_merger_model',
        NULL,
        '["cq_592c9172d4814ad1","cq_9f5ac0cd3d38479c","cq_a07d7dc8e24d40c5","cq_f426d73a85ff4850","cq_87154a13fcb64170","cq_e826eab821974705"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_pe_fund_lesson',
        'module_pe_fund_mechanics',
        'lesson',
        'LPs, GPs, fees and carry',
        1,
        'concept_pe_fund_mechanics',
        NULL,
        '["cq_b9f20ed1f54a4d5e","cq_2d3a9f2c7c184c55","cq_0fa258ed5a9040a5","cq_8eb0105103784087"]'::jsonb,
        $$## Who is in a fund

A private equity fund is usually a limited partnership. **Limited partners (LPs)** — pension funds, endowments, sovereign wealth funds, insurers, family offices — commit capital. The **general partner (GP)**, the PE firm, makes and manages the investments and usually commits 1–5% itself.

## Life of a fund

- **Fundraising** — LPs sign commitments; nothing is paid up front.
- **Investment period** (about 5 years) — the GP makes **capital calls** as deals close.
- **Harvest period** — portfolio companies are improved and exited; proceeds are distributed.
- **Fund life** — typically 10 years plus extensions.

Early on, fees and write-downs make returns negative before exits arrive — the **J-curve**.

## Fees and carry: "2 and 20"

- **Management fee** — roughly 1.5–2% a year of committed capital during the investment period, often stepping down to invested capital afterwards. It pays for the GP's team and operations.
- **Carried interest** — the GP's share of profits, typically **20%**, earned only after LPs get their capital back plus a **preferred return (hurdle)**, commonly **8%** a year.

## The distribution waterfall

1. Return of capital to LPs.
2. Preferred return to LPs (the hurdle).
3. **GP catch-up** until the GP has received 20% of profits so far.
4. 80 / 20 split thereafter.

A **European (whole-fund)** waterfall applies this to the fund as a whole; an **American (deal-by-deal)** waterfall pays carry deal by deal and usually has a **clawback** in case later deals lose money.

### Worked example

LPs contribute 1,000 and the fund returns 1,800 in total. Profit = 800. The hurdle is cleared and there is a full catch-up, so the GP's carry = 20% × 800 = **160** and LPs receive **1,640** — a net multiple of 1.64x before fees versus a gross 1.8x.

## Measuring performance

| Metric | Meaning |
| --- | --- |
| IRR | time-weighted annual return on cash flows |
| MOIC / TVPI | total value (distributed + remaining) ÷ paid-in capital |
| DPI | distributions ÷ paid-in capital — cash actually returned |
| RVPI | remaining value ÷ paid-in capital |

**MOIC vs IRR:** MOIC measures how much money you made; IRR measures how fast. A quick flip can have a high IRR but a low MOIC; a long hold can have a high MOIC but a modest IRR. LPs want both, and increasingly care about DPI.

## Why dividend recaps and quick exits matter

A **dividend recap** borrows at the portfolio company to pay the fund a dividend. It returns cash early, which raises IRR and DPI without an exit, at the cost of more leverage on the company.

## Interview angles

1. "How does a PE firm make money?" Fees plus carry, and carry depends on beating the hurdle.
2. "Why might a GP prefer IRR over MOIC?" Carry and fundraising track IRR, but a very short hold may not return enough absolute dollars.
3. "Gross vs net returns?" Net returns are after fees and carry — what LPs actually earn.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_pe_waterfall_diagram',
        'module_pe_fund_mechanics',
        'diagram',
        'Distribution waterfall',
        2,
        'concept_pe_fund_mechanics',
        'diag_pe_distribution_waterfall',
        '["cq_7c29d259b4004a54","cq_6b9dd095581940c3","cq_d5c2dc215d83443f"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_pe_returns_diagram',
        'module_pe_fund_mechanics',
        'diagram',
        'Returns attribution',
        3,
        'concept_pe_fund_mechanics',
        'diag_returns_attribution',
        '["cq_4183f81f841048f3","cq_9f7f7b3a2b6d4761","cq_1e567a8fcaa645a7"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_pe_diligence_lab',
        'module_pe_fund_mechanics',
        'concept_lab',
        'Investment thesis and quality of earnings',
        4,
        'concept_pe_fund_mechanics',
        NULL,
        '["cq_ed16aac9bc6e4e7e","cq_859475d0c1c94661","cq_1c79fbadc5a346ed","cq_699ec9fe28eb4027"]'::jsonb,
        $$## From idea to investment committee

Before a sponsor bids, the deal team writes an **investment thesis** and tests it through diligence. The memo that goes to the investment committee answers four questions: **why this business, why now, why us, and what could go wrong.**

## A thesis framework

1. **Market** — size, growth, cyclicality, competitive dynamics.
2. **Business quality** — recurring revenue, customer retention, pricing power, margins, cash conversion.
3. **Value creation plan** — the specific levers: organic growth, pricing, cost programme, add-on acquisitions, working capital, professionalising management.
4. **Returns** — base, upside and downside cases, with the deal still clearing a minimum return in the downside.
5. **Key risks and mitigants** — customer concentration, technology disruption, leverage, key-person risk.
6. **Exit** — who buys it in five years, and at what multiple.

A strong interview answer is specific: "Three reasons: 85% recurring revenue with 95% gross retention, a fragmented market where we can buy add-ons at 6–7x versus our 11x entry, and a pricing gap versus the market leader."

## Quality of earnings (QoE)

A **QoE report**, usually by an accounting firm, tests whether reported EBITDA is real, recurring and cash-backed. Because the purchase price is a **multiple of adjusted EBITDA**, every adjustment is worth that multiple in value.

### Worked example

Management presents EBITDA of 50. Diligence finds:

- A one-off gain on an asset sale of 5 included in EBITDA → remove, **−5**
- A genuine one-time litigation cost of 3 → add back, **+3**
- The founder is paid 1 but a market-rate CEO costs 3 → normalise, **−2**

Diligence-adjusted EBITDA = 50 − 5 + 3 − 2 = **46**. At 10.0x, that is **40 less value** than the headline number — enough to change the bid.

QoE also looks at revenue recognition, normalised working capital (to set the **working capital peg** in the purchase agreement), capex needs and customer concentration.

## Other diligence workstreams

| Workstream | Key question |
| --- | --- |
| Commercial | Is the market and competitive position as good as claimed? |
| Financial / QoE | Is EBITDA real and recurring? |
| Legal | Contracts, litigation, change-of-control clauses |
| Tax | Exposures and structuring |
| IT / cyber | Scalability and risk |
| Management | Can this team execute the plan? |
| ESG | Regulatory and reputational risk |

## Red flags interviewers expect you to spot

- Revenue growth driven by one customer or aggressive recognition.
- Rising receivables or inventory relative to revenue (earnings not converting to cash).
- Large, repeated "one-off" adjustments.
- Capex below depreciation for years (underinvestment).

## Why buy a company in a "risky" industry?

Sponsors buy technology and other volatile sectors when revenue is recurring (subscriptions), switching costs are high, and growth offsets lower leverage. They adapt the structure — less debt, more equity, sometimes growth or minority deals.

## Interview answer template

"I'd underwrite the thesis on market, business quality, a specific value creation plan and the downside case, then test it in diligence — commercial work on the market and a QoE on EBITDA, since every dollar of EBITDA is worth the purchase multiple."$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_pe_drill',
        'module_pe_fund_mechanics',
        'drill',
        'Sponsor judgement drill',
        5,
        'concept_pe_fund_mechanics',
        NULL,
        '["cq_95bbf5673ab7428d","cq_848e98a343c14dc3","cq_c8183b1f88294c25","cq_7ef604ebf0254239","cq_3279968442654676"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_behavioural_lesson',
        'module_behavioural_story',
        'lesson',
        'Personal story structure',
        1,
        'concept_behavioural_story',
        NULL,
        '["cq_818c9674c12f4d24","cq_a5c69c8756e34410","cq_41552d7f7ee6448c","cq_5b7ddd40a0de43d2"]'::jsonb,
        $$## What fit interviews test

Behavioural questions check three things: **can you communicate clearly, do you really want this job, and will people want to work with you at 2 a.m.** Technical answers get you to the next round; fit answers often decide the offer.

## "Walk me through your resume"

Aim for **60–90 seconds** with a clear arc:

1. **Beginning** — where you grew up or studied, and one detail that explains your interests.
2. **Middle** — two or three experiences, each with a **turning point**: what you did, what you learned, and why it pulled you towards finance.
3. **End** — why this role, why now, and why you are ready.

Do not recite every bullet. The interviewer has the CV; they want the **story that connects it**.

### Example skeleton

"I studied economics at State, where I joined the investment club and pitched a consumer stock that taught me how much I enjoy digging into a business. That led to a summer at a mid-market advisory firm, where I built a comps set for a sell-side deal and saw how the analysis shaped the client's decision. This year I've focused on deepening my modelling skills, which is why I'm excited about your M&A group — the deal flow in industrials matches what I've enjoyed most."

## "Why banking?" / "Why private equity?"

Give **two or three concrete reasons** tied to your experience: steep learning curve, exposure to transactions and senior decision makers, the analytical work you already enjoyed. For PE: thinking like an owner, long-term value creation, and evaluating businesses as investments. Avoid "money" and avoid generic "fast-paced environment" lines without evidence.

## "Why our firm?"

Show research you could only have done by engaging: a recent deal and why it interested you, the group's sector focus, conversations with people there (name them if appropriate), culture or training. Tie at least one point back to your own story.

## Strengths, weaknesses and "why should we hire you?"

- **Strength:** one clear strength plus a short piece of evidence.
- **Weakness:** a real but manageable weakness, what you did about it, and the result. Not "I work too hard".
- **Why hire you:** three sentences — skills, evidence, motivation.

## Delivery

- Answer the question first, then support it.
- Keep answers to one or two minutes; pause and let the interviewer follow up.
- Be consistent: your "why banking" must match your resume story.
- Prepare questions for the interviewer that show genuine interest.

## Practise like a technical

Write bullet outlines, not scripts, and rehearse out loud. Record yourself once and cut filler. Then build the story bank in the next checkpoint so you can answer any "tell me about a time" question.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_behavioural_star_lab',
        'module_behavioural_story',
        'concept_lab',
        'STAR story bank',
        2,
        'concept_behavioural_story',
        NULL,
        '["cq_b6598139b7924d8c","cq_0accdf28b5a443fd","cq_d6ce457685774cf1","cq_aa0f609db1a04779","cq_a167bc0c121a49b6","cq_238fafacc33a49d4"]'::jsonb,
        $$## Why a story bank

"Tell me about a time when…" questions are unpredictable in wording but predictable in theme. Instead of memorising answers, prepare **five or six stories** that each cover several themes, and use a consistent structure so you never ramble.

## The STAR (+R) structure

1. **Situation** — one or two sentences of context. Who, where, what was at stake.
2. **Task** — your specific responsibility or the problem you owned.
3. **Action** — what **you** did, step by step. This should be the longest part and use "I", not "we".
4. **Result** — the outcome, quantified where possible.
5. **Reflection** — what you learned or would do differently. This is what separates good answers from great ones.

Aim for about 90 seconds: roughly 15% situation and task, 60% action, 25% result and reflection.

## Themes to cover

| Theme | Typical question |
| --- | --- |
| Teamwork | Tell me about a team project. |
| Conflict | Describe a situation where a team did not work as intended. |
| Leadership | What was the most difficult situation you faced as a leader? |
| Failure / mistake | What was your greatest failure? |
| Ethics | Tell me about an ethical challenge. |
| Attention to detail | Tell me about a time you made an error in your work. |
| Pressure / time management | Describe juggling competing deadlines. |

Map each of your stories to two or three themes so a small bank covers the whole list.

## Worked example: a mistake in your work

- **Situation:** "During my internship I was building a comps table for a client presentation due the next morning."
- **Task:** "I owned the multiples and the summary page."
- **Action:** "Late that evening I noticed one peer's EBITDA was on a different fiscal year end, which inflated its multiple. I told my associate straight away, recalendarised the peer, re-ran the medians, and added a check column to flag fiscal year mismatches."
- **Result:** "The median moved from 9.4x to 8.9x, the deck went out on time with the corrected range, and the team adopted the check column on the next two deals."
- **Reflection:** "I learned to build checks in from the start and to raise problems early rather than try to hide them."

Notice what it shows: ownership, attention to detail, honesty under pressure and a lasting fix — exactly what a banker wants from an analyst.

## Common mistakes

1. Too much situation, too little action.
2. "We" throughout, so the interviewer cannot tell what you did.
3. No result, or a result with no numbers.
4. A "failure" that is not really a failure, or one that blames others.
5. Stories that contradict your resume walk-through.

## How to practise

Write each story as five bullets (S, T, A, R, R). Say it aloud against a 90-second timer. Then answer three random questions from the table using only your bank — if a question does not fit any story, add one.$$,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    ),
    (
        'chk_behavioural_drill',
        'module_behavioural_story',
        'drill',
        'Why this firm and why this role',
        3,
        'concept_behavioural_story',
        NULL,
        '["cq_4b80e96097924476","cq_d6630e525d6742e6","cq_15589ebea2ea4f1d","cq_16711e138ef74362","cq_c5a206272f864f6d","cq_eef790f3cb184a10"]'::jsonb,
        NULL,
        '{"seed":"060_curriculum_lessons"}'::jsonb
    )
ON CONFLICT (id) DO UPDATE SET
    module_id = EXCLUDED.module_id,
    kind = EXCLUDED.kind,
    title = EXCLUDED.title,
    position = EXCLUDED.position,
    concept_id = EXCLUDED.concept_id,
    diagram_id = EXCLUDED.diagram_id,
    question_ids = EXCLUDED.question_ids,
    body_markdown = EXCLUDED.body_markdown,
    metadata_json = learning_module_checkpoints.metadata_json || EXCLUDED.metadata_json,
    updated_at = now();
