#!/usr/bin/env npx tsx
/**
 * Render the Mode B curriculum source (apps/web/lib/data/curriculum/*) into
 * Neon migrations 059–061 and the no-DB question → diagram link map.
 *
 *   npx tsx scripts/curriculum/build-migrations.ts          # write files
 *   npx tsx scripts/curriculum/build-migrations.ts --check  # fail if stale
 *
 * Outputs:
 *   migrations/059_diagrams_core.sql            diagrams + versions + question links
 *   migrations/060_curriculum_lessons.sql       concepts, modules, checkpoints, lessons
 *   migrations/061_interactive_diagrams.sql     interactive-json quizzes + quiz checkpoints
 *   apps/web/lib/data/curriculum/question-diagram-links.generated.ts
 *
 * Question links are computed by keyword rules
 * (apps/web/lib/data/curriculum/question-diagram-rules.ts) against the wording
 * in exports/questions.jsonl, so only ids present in the export are linked.
 * The SQL additionally joins canonical.canonical_questions, so a database
 * without those questions simply gets fewer rows instead of FK errors.
 */
import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import {
  CURRICULUM_CONCEPTS,
  CURRICULUM_DIAGRAMS,
  CURRICULUM_MODULES,
  validateCurriculum,
  type CurriculumCheckpoint,
  type CurriculumDiagram,
} from "../../apps/web/lib/data/curriculum/index"
import {
  linkDiagramsForQuestion,
  type QuestionDiagramLink,
} from "../../apps/web/lib/data/curriculum/question-diagram-rules"

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, "../..")
const GENERATOR = "scripts/curriculum/build-migrations.ts"

type ExportQuestion = { id: string; canonical_wording: string; topic: string | null }

function loadQuestions(): ExportQuestion[] {
  return readFileSync(path.join(repoRoot, "exports/questions.jsonl"), "utf8")
    .split("\n")
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line) as ExportQuestion)
}

/** Single-quoted SQL literal. */
function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL"
  return `'${value.replace(/'/g, "''")}'`
}

/** $$-quoted literal — the migrate runner's splitter understands $$ only. */
function dollar(value: string): string {
  if (value.includes("$$")) throw new Error(`value contains $$: ${value.slice(0, 60)}`)
  return `$$${value}$$`
}

function jsonLit(value: unknown): string {
  return `${lit(JSON.stringify(value))}::jsonb`
}

function header(file: string, lines: string[]): string {
  const body = [
    `-- ${file}`,
    ...lines.map((line) => `-- ${line}`),
    `-- Generated by ${GENERATOR} from apps/web/lib/data/curriculum. Do not edit by hand.`,
    "",
  ]
  for (const line of body) {
    if (line.startsWith("--") && line.includes(";")) {
      throw new Error(`semicolon in SQL comment: ${line}`)
    }
  }
  return body.join("\n")
}

function diagramSql(diagrams: CurriculumDiagram[]): string {
  const rows = diagrams
    .map(
      (d) =>
        `    (${lit(d.id)}, ${lit(d.slug)}, ${lit(d.title)}, ${lit(d.diagram_type)}, ${lit(d.a11y)})`,
    )
    .join(",\n")
  const versions = diagrams
    .map(
      (d) =>
        `    (\n        ${lit(`${d.id}_v${d.version}`)},\n        ${lit(d.id)},\n        ${lit(d.version)},\n        ${lit(d.format)},\n        ${dollar(d.body)}\n    )`,
    )
    .join(",\n")
  return `INSERT INTO canonical.diagrams (id, slug, title, diagram_type, a11y_fallback)
VALUES
${rows}
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    diagram_type = EXCLUDED.diagram_type,
    a11y_fallback = EXCLUDED.a11y_fallback;

INSERT INTO canonical.diagram_versions (id, diagram_id, version, format, body)
VALUES
${versions}
ON CONFLICT (diagram_id, version) DO UPDATE SET
    format = EXCLUDED.format,
    body = EXCLUDED.body;
`
}

function questionLinkSql(links: QuestionDiagramLink[]): string {
  if (links.length === 0) return ""
  const rows = links
    .map((l) => `    (${lit(l.question_id)}, ${lit(l.diagram_id)}, ${l.relevance.toFixed(2)})`)
    .join(",\n")
  return `INSERT INTO canonical.question_diagrams (question_id, diagram_id, relevance)
SELECT v.question_id, v.diagram_id, v.relevance
FROM (VALUES
${rows}
) AS v(question_id, diagram_id, relevance)
JOIN canonical.canonical_questions q ON q.id = v.question_id
JOIN canonical.diagrams d ON d.id = v.diagram_id
ON CONFLICT (question_id, diagram_id) DO UPDATE SET
    relevance = EXCLUDED.relevance;
`
}

function checkpointSql(
  rows: Array<{ moduleId: string; checkpoint: CurriculumCheckpoint }>,
): string {
  const values = rows
    .map(({ moduleId, checkpoint: c }) => {
      const body = c.body_markdown ? dollar(c.body_markdown) : "NULL"
      const metadata = { seed: "060_curriculum_lessons", ...(c.metadata ?? {}) }
      return `    (
        ${lit(c.id)},
        ${lit(moduleId)},
        ${lit(c.kind)},
        ${lit(c.title)},
        ${c.position},
        ${lit(c.concept_id)},
        ${c.diagram_id ? lit(c.diagram_id) : "NULL"},
        ${jsonLit(c.question_ids)},
        ${body},
        ${jsonLit(metadata)}
    )`
    })
    .join(",\n")
  return `INSERT INTO canonical.learning_module_checkpoints (
    id, module_id, kind, title, position, concept_id, diagram_id, question_ids, body_markdown, metadata_json
)
VALUES
${values}
ON CONFLICT (id) DO UPDATE SET
    module_id = EXCLUDED.module_id,
    kind = EXCLUDED.kind,
    title = EXCLUDED.title,
    position = EXCLUDED.position,
    concept_id = EXCLUDED.concept_id,
    diagram_id = EXCLUDED.diagram_id,
    question_ids = EXCLUDED.question_ids,
    body_markdown = EXCLUDED.body_markdown,
    metadata_json = learning_module_checkpoints.metadata_json || EXCLUDED.metadata_json,
    updated_at = now();
`
}

function curriculumSql(): string {
  const concepts = CURRICULUM_CONCEPTS.map(
    (c) =>
      `    (${lit(c.id)}, ${lit(c.slug)}, ${lit(c.title)}, ${lit(c.summary)}, ${lit(c.track)}, ${jsonLit({ domain: c.domain, prerequisites: c.prerequisites, seed: "060_curriculum_lessons" })}, true)`,
  ).join(",\n")

  const modules = CURRICULUM_MODULES.map(
    (m) =>
      `    (${lit(m.id)}, ${lit(m.slug)}, ${lit(m.title)}, ${lit(m.summary)}, ${lit(m.track)}, ${lit(m.domain)}, ${m.estimated_minutes}, ${jsonLit({ seed: "060_curriculum_lessons", level: m.level, order: m.order })}, true)`,
  ).join(",\n")

  const prereqPairs = CURRICULUM_MODULES.flatMap((m) =>
    m.prereq_module_ids.map((p) => `    (${lit(m.id)}, ${lit(p)})`),
  )
  const moduleIdList = CURRICULUM_MODULES.map((m) => lit(m.id)).join(", ")
  const moduleConcepts = CURRICULUM_MODULES.map(
    (m) => `    (${lit(m.id)}, ${lit(m.concept_id)})`,
  ).join(",\n")

  const nonQuiz = CURRICULUM_MODULES.flatMap((m) =>
    m.checkpoints
      .filter((c) => !isInteractiveCheckpoint(c))
      .map((checkpoint) => ({ moduleId: m.id, checkpoint })),
  )

  return `INSERT INTO canonical.concepts (id, slug, title, summary, track, metadata_json, publishable)
VALUES
${concepts}
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    track = EXCLUDED.track,
    metadata_json = concepts.metadata_json || EXCLUDED.metadata_json,
    publishable = EXCLUDED.publishable,
    updated_at = now();

INSERT INTO canonical.learning_modules (
    id, slug, title, summary, track, domain, estimated_minutes, metadata_json, publishable
)
VALUES
${modules}
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    track = EXCLUDED.track,
    domain = EXCLUDED.domain,
    estimated_minutes = EXCLUDED.estimated_minutes,
    metadata_json = learning_modules.metadata_json || EXCLUDED.metadata_json,
    publishable = EXCLUDED.publishable,
    updated_at = now();

DELETE FROM canonical.learning_module_prerequisites p
WHERE p.module_id IN (${moduleIdList})
  AND NOT EXISTS (
    SELECT 1
    FROM (VALUES
${prereqPairs.map((pair) => `    ${pair.trim()}`).join(",\n")}
    ) AS keep(module_id, prerequisite_module_id)
    WHERE keep.module_id = p.module_id
      AND keep.prerequisite_module_id = p.prerequisite_module_id
  );

INSERT INTO canonical.learning_module_prerequisites (module_id, prerequisite_module_id)
VALUES
${prereqPairs.join(",\n")}
ON CONFLICT (module_id, prerequisite_module_id) DO NOTHING;

INSERT INTO canonical.learning_module_concepts (module_id, concept_id)
VALUES
${moduleConcepts}
ON CONFLICT (module_id, concept_id) DO NOTHING;

${checkpointSql(nonQuiz)}`
}

const INTERACTIVE_IDS = new Set(
  CURRICULUM_DIAGRAMS.filter((d) => d.format === "interactive-json").map((d) => d.id),
)

function isInteractiveCheckpoint(checkpoint: CurriculumCheckpoint): boolean {
  return Boolean(checkpoint.diagram_id && INTERACTIVE_IDS.has(checkpoint.diagram_id))
}

function buildLinks(questions: ExportQuestion[]): QuestionDiagramLink[] {
  const links: QuestionDiagramLink[] = []
  for (const question of questions) {
    for (const link of linkDiagramsForQuestion({
      wording: question.canonical_wording,
      topic: question.topic,
    })) {
      links.push({ question_id: question.id, ...link })
    }
  }
  return links.sort(
    (a, b) => a.diagram_id.localeCompare(b.diagram_id) || a.question_id.localeCompare(b.question_id),
  )
}

function linksModule(links: QuestionDiagramLink[]): string {
  const byQuestion = new Map<string, Array<[string, number]>>()
  for (const link of links) {
    const list = byQuestion.get(link.question_id) ?? []
    list.push([link.diagram_id, link.relevance])
    byQuestion.set(link.question_id, list)
  }
  const entries = [...byQuestion.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([questionId, list]) =>
        `  ${questionId}: [${list
          .sort((a, b) => b[1] - a[1])
          .map(([d, r]) => `["${d}", ${r}]`)
          .join(", ")}],`,
    )
    .join("\n")
  return `/**
 * Generated by ${GENERATOR} — do not edit by hand.
 * canonical question id → [diagram id, relevance] (mirrors canonical.question_diagrams).
 */
export const QUESTION_DIAGRAM_LINKS: Record<string, Array<[string, number]>> = {
${entries}
}
`
}

function main() {
  const check = process.argv.includes("--check")
  const questions = loadQuestions()
  const errors = validateCurriculum(new Set(questions.map((q) => q.id)))
  if (errors.length > 0) {
    console.error("Curriculum validation failed:\n" + errors.map((e) => `  - ${e}`).join("\n"))
    process.exit(1)
  }

  const links = buildLinks(questions)
  const mermaid = CURRICULUM_DIAGRAMS.filter((d) => d.format === "mermaid")
  const interactive = CURRICULUM_DIAGRAMS.filter((d) => d.format === "interactive-json")
  const mermaidLinks = links.filter((l) => !INTERACTIVE_IDS.has(l.diagram_id))
  const interactiveLinks = links.filter((l) => INTERACTIVE_IDS.has(l.diagram_id))

  const upgraded = mermaid.filter((d) => d.version !== "1").length
  const sql059 = [
    header("059_diagrams_core.sql", [
      "P2.9 diagram coverage (plan 2026-09-23-001).",
      `Upgrades ${upgraded} existing mermaid diagrams to richer version-2 bodies and adds`,
      `${mermaid.length - upgraded} new ones (comps, full 3-statement, debt schedule, working capital,`,
      "merger model, returns attribution, DDM, football field, restructuring and PE waterfalls).",
      `Links ${new Set(mermaidLinks.map((l) => l.question_id)).size} export questions to diagrams by keyword rules (${mermaidLinks.length} rows).`,
      "Rows whose question is absent from canonical.canonical_questions are skipped by the join.",
    ]),
    diagramSql(mermaid),
    questionLinkSql(mermaidLinks),
  ].join("\n")

  const sql060 = [
    header("060_curriculum_lessons.sql", [
      "P2.10 curriculum fill (plan 2026-09-23-001).",
      `${CURRICULUM_MODULES.length} modules covering accounting, EV, comps, DCF, LBO, M&A, PE fund mechanics`,
      "and behavioural. Real lesson body_markdown for every lesson and concept lab, at least three",
      "export question ids per checkpoint (replaces the 039 seeds, fixing the duplicated LBO id),",
      "and diagram checkpoints pointed at the 059 diagrams.",
    ]),
    curriculumSql(),
  ].join("\n")

  const quizCheckpoints = CURRICULUM_MODULES.flatMap((m) =>
    m.checkpoints
      .filter((c) => isInteractiveCheckpoint(c))
      .map((checkpoint) => ({ moduleId: m.id, checkpoint })),
  )
  const sql061 = [
    header("061_interactive_diagrams.sql", [
      "P7.2 interactive diagrams (plan 2026-09-23-001).",
      `Seeds ${interactive.length} interactive-json diagram versions (InteractiveDiagramSchema in`,
      "packages/contracts/src/diagram.ts) and wires them as graded diagram quiz checkpoints.",
      "These bodies render with DiagramFillBlank, never with Mermaid.",
    ]),
    diagramSql(interactive),
    checkpointSql(quizCheckpoints),
    questionLinkSql(interactiveLinks),
  ].join("\n")

  const outputs: Array<[string, string]> = [
    ["migrations/059_diagrams_core.sql", sql059],
    ["migrations/060_curriculum_lessons.sql", sql060],
    ["migrations/061_interactive_diagrams.sql", sql061],
    ["apps/web/lib/data/curriculum/question-diagram-links.generated.ts", linksModule(links)],
  ]

  let stale = false
  for (const [relative, content] of outputs) {
    const full = path.join(repoRoot, relative)
    if (check) {
      let current = ""
      try {
        current = readFileSync(full, "utf8")
      } catch {
        current = ""
      }
      if (current !== content) {
        console.error(`stale: ${relative}`)
        stale = true
      }
    } else {
      writeFileSync(full, content)
      console.log(`wrote ${relative}`)
    }
  }
  const linkedQuestions = new Set(links.map((l) => l.question_id)).size
  console.log(
    `${CURRICULUM_DIAGRAMS.length} diagrams, ${CURRICULUM_MODULES.length} modules, ${links.length} question links over ${linkedQuestions}/${questions.length} export questions`,
  )
  if (stale) process.exit(1)
}

main()
